package com.xmen.model;

import org.antlr.v4.runtime.*;
import org.antlr.v4.runtime.atn.ATN;
import org.antlr.v4.runtime.atn.ATNDeserializer;
import org.antlr.v4.runtime.atn.ParserATNSimulator;
import org.antlr.v4.runtime.atn.PredictionContextCache;
import org.antlr.v4.runtime.dfa.DFA;
import org.antlr.v4.runtime.tree.ParseTreeVisitor;

import java.util.List;

/**
 * Tamarin parser implementation generated by ANTLR. This class handles parsing of Tamarin protocol
 * specifications, supporting various components including built-ins, equations, functions, and
 * protocol rules. The parser builds an abstract syntax tree from Tamarin specifications, supporting
 * the hierarchical structure of protocols, facts, terms, and expressions.
 */
@SuppressWarnings({"deprecation", "unchecked"})
public class TamarinParser extends Parser {
  protected static final DFA[] _decisionToDFA;
  protected static final PredictionContextCache _sharedContextCache;
  public static final int T__0 = 1;
  public static final int T__1 = 2;
  public static final int T__2 = 3;
  public static final int T__3 = 4;
  public static final int T__4 = 5;
  public static final int T__5 = 6;
  public static final int T__6 = 7;
  public static final int T__7 = 8;
  public static final int T__8 = 9;
  public static final int T__9 = 10;
  public static final int T__10 = 11;
  public static final int T__11 = 12;
  public static final int T__12 = 13;
  public static final int T__13 = 14;
  public static final int T__14 = 15;
  public static final int T__15 = 16;
  public static final int T__16 = 17;
  public static final int T__17 = 18;
  public static final int T__18 = 19;
  public static final int T__19 = 20;
  public static final int T__20 = 21;
  public static final int T__21 = 22;
  public static final int T__22 = 23;
  public static final int T__23 = 24;
  public static final int T__24 = 25;
  public static final int T__25 = 26;
  public static final int T__26 = 27;
  public static final int T__27 = 28;
  public static final int T__28 = 29;
  public static final int T__29 = 30;
  public static final int T__30 = 31;
  public static final int T__31 = 32;
  public static final int T__32 = 33;
  public static final int T__33 = 34;
  public static final int T__34 = 35;
  public static final int T__35 = 36;
  public static final int T__36 = 37;
  public static final int T__37 = 38;
  public static final int T__38 = 39;
  public static final int T__39 = 40;
  public static final int T__40 = 41;
  public static final int T__41 = 42;
  public static final int T__42 = 43;
  public static final int T__43 = 44;
  public static final int T__44 = 45;
  public static final int T__45 = 46;
  public static final int T__46 = 47;
  public static final int T__47 = 48;
  public static final int T__48 = 49;
  public static final int T__49 = 50;
  public static final int T__50 = 51;
  public static final int T__51 = 52;
  public static final int T__52 = 53;
  public static final int ALPHA = 54;
  public static final int SQUOTE = 55;
  public static final int TILDQ = 56;
  public static final int WS = 57;
  public static final int COMMENT = 58;
  public static final int LINE_COMMENT = 59;
  public static final int RULE_theory = 0;
  public static final int RULE_component = 1;
  public static final int RULE_built_in = 2;
  public static final int RULE_builtin_name = 3;
  public static final int RULE_equations = 4;
  public static final int RULE_equation_symbol = 5;
  public static final int RULE_functions = 6;
  public static final int RULE_function_symbol = 7;
  public static final int RULE_protocolrule = 8;
  public static final int RULE_genericrule = 9;
  public static final int RULE_let_block = 10;
  public static final int RULE_fact = 11;
  public static final int RULE_terms = 12;
  public static final int RULE_fact_identifier = 13;
  public static final int RULE_multterm = 14;
  public static final int RULE_expterm = 15;
  public static final int RULE_term = 16;
  public static final int RULE_group_of_terms = 17;
  public static final int RULE_nullary_fun = 18;
  public static final int RULE_binary_app = 19;
  public static final int RULE_binary_fun = 20;
  public static final int RULE_nary_app = 21;
  public static final int RULE_literal = 22;
  public static final int RULE_identifier = 23;
  public static final int RULE_natural = 24;
  public static final int RULE_digit = 25;
  public static final String[] ruleNames;
  private static final String[] _LITERAL_NAMES;
  private static final String[] _SYMBOLIC_NAMES;
  public static final Vocabulary VOCABULARY;
  public static final String[] tokenNames;
  public static final ATN _ATN;

  /**
   * Makes the rule names for the lexer.
   *
   * @return an array of token names
   */
  private static String[] makeRuleNames() {
    return new String[] {
      "theory",
      "component",
      "built_in",
      "builtin_name",
      "equations",
      "equation_symbol",
      "functions",
      "function_symbol",
      "protocolrule",
      "genericrule",
      "let_block",
      "fact",
      "terms",
      "fact_identifier",
      "multterm",
      "expterm",
      "term",
      "group_of_terms",
      "nullary_fun",
      "binary_app",
      "binary_fun",
      "nary_app",
      "literal",
      "identifier",
      "natural",
      "digit"
    };
  }

  /**
   * Creates an array of literal names for the lexer tokens.
   *
   * @return an array of literal names
   */
  private static String[] makeLiteralNames() {
    return new String[] {
      null,
      "'end'",
      "'builtins'",
      "':'",
      "','",
      "'diffie-hellman'",
      "'bilinear-pairing'",
      "'multiset'",
      "'xor'",
      "'symmetric-encryption'",
      "'asymmetric-encryption'",
      "'signing'",
      "'revealing-signing'",
      "'hashing'",
      "'equations'",
      "'='",
      "'functions'",
      "'/'",
      "'[private]'",
      "'rule'",
      "'['",
      "']'",
      "'-->'",
      "'--['",
      "']->'",
      "'let'",
      "'in'",
      "'('",
      "')'",
      "'!'",
      "'*'",
      "'^'",
      "'<'",
      "'>'",
      "'all'",
      "'{'",
      "'}'",
      "'aenc'",
      "'sign'",
      "'pk'",
      "'senc'",
      "'$'",
      "'~'",
      "'#'",
      "'0'",
      "'1'",
      "'2'",
      "'3'",
      "'4'",
      "'5'",
      "'6'",
      "'7'",
      "'8'",
      "'9'",
      null,
      "'''",
      "'~''"
    };
  }

  /**
   * Creates an array of symbolic names for the lexer tokens.
   *
   * @return an array of symbolic names
   */
  private static String[] makeSymbolicNames() {
    return new String[] {
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "ALPHA",
      "SQUOTE",
      "TILDQ",
      "WS",
      "COMMENT",
      "LINE_COMMENT"
    };
  }

  /**
   * Gets the vocabulary for the lexer.
   *
   * @return the vocabulary object containing literal and symbolic names
   */
  public String[] getTokenNames() {
    return tokenNames;
  }

  /**
   * Gets the vocabulary for the lexer.
   *
   * @return the vocabulary object containing literal, symbolic names and display names
   */
  public Vocabulary getVocabulary() {
    return VOCABULARY;
  }

  /**
   * Gets the grammar file name for the lexer.
   *
   * @return the name of the grammar file
   */
  public String getGrammarFileName() {
    return "Tamarin.g4";
  }

  /**
   * Gets the Rule names for the lexer.
   *
   * @return an array of rule names
   */
  public String[] getRuleNames() {
    return ruleNames;
  }

  /**
   * Gets the serialized ATN for the lexer.
   *
   * @return the serialized ATN string
   */
  public String getSerializedATN() {
    return "\u0003悋Ꜫ脳맭䅼㯧瞆奤\u0003=ĩ\u0004\u0002\t\u0002\u0004\u0003\t\u0003\u0004\u0004\t\u0004\u0004\u0005\t\u0005\u0004\u0006\t\u0006\u0004\u0007\t\u0007\u0004\b\t\b\u0004\t\t\t\u0004\n\t\n\u0004\u000b\t\u000b\u0004\f\t\f\u0004\r\t\r\u0004\u000e\t\u000e\u0004\u000f\t\u000f\u0004\u0010\t\u0010\u0004\u0011\t\u0011\u0004\u0012\t\u0012\u0004\u0013\t\u0013\u0004\u0014\t\u0014\u0004\u0015\t\u0015\u0004\u0016\t\u0016\u0004\u0017\t\u0017\u0004\u0018\t\u0018\u0004\u0019\t\u0019\u0004\u001a\t\u001a\u0004\u001b\t\u001b\u0003\u0002\u0007\u00028\n\u0002\f\u0002\u000e\u0002;\u000b\u0002\u0003\u0002\u0003\u0002\u0003\u0003\u0003\u0003\u0003\u0003\u0003\u0003\u0005\u0003C\n\u0003\u0003\u0004\u0003\u0004\u0003\u0004\u0003\u0004\u0003\u0004\u0007\u0004J\n\u0004\f\u0004\u000e\u0004M\u000b\u0004\u0003\u0005\u0003\u0005\u0003\u0006\u0003\u0006\u0003\u0006\u0003\u0006\u0003\u0006\u0007\u0006V\n\u0006\f\u0006\u000e\u0006Y\u000b\u0006\u0003\u0007\u0003\u0007\u0003\u0007\u0003\u0007\u0003\b\u0003\b\u0003\b\u0003\b\u0003\b\u0007\bd\n\b\f\b\u000e\bg\u000b\b\u0003\t\u0003\t\u0003\t\u0003\t\u0003\t\u0003\t\u0003\t\u0003\t\u0003\t\u0005\tr\n\t\u0003\n\u0003\n\u0003\n\u0003\n\u0003\n\u0003\n\u0003\n\u0003\n\u0003\n\u0003\n\u0003\n\u0005\n\u007f\n\n\u0003\u000b\u0003\u000b\u0003\u000b\u0003\u000b\u0007\u000b\u0085\n\u000b\f\u000b\u000e\u000b\u0088\u000b\u000b\u0003\u000b\u0003\u000b\u0003\u000b\u0003\u000b\u0003\u000b\u0003\u000b\u0007\u000b\u0090\n\u000b\f\u000b\u000e\u000b\u0093\u000b\u000b\u0003\u000b\u0003\u000b\u0005\u000b\u0097\n\u000b\u0003\u000b\u0003\u000b\u0003\u000b\u0003\u000b\u0007\u000b\u009d\n\u000b\f\u000b\u000e\u000b \u000b\u000b\u0003\u000b\u0003\u000b\u0003\u000b\u0003\u000b\u0005\u000b¦\n\u000b\u0003\f\u0003\f\u0003\f\u0003\f\u0003\f\u0006\f\u00ad\n\f\r\f\u000e\f®\u0003\f\u0003\f\u0003\r\u0003\r\u0003\r\u0003\r\u0003\r\u0003\r\u0003\r\u0003\r\u0003\r\u0005\r¼\n\r\u0003\u000e\u0003\u000e\u0003\u000e\u0007\u000eÁ\n\u000e\f\u000e\u000e\u000eÄ\u000b\u000e\u0003\u000f\u0003\u000f\u0003\u000f\u0005\u000fÉ\n\u000f\u0003\u0010\u0003\u0010\u0003\u0010\u0007\u0010Î\n\u0010\f\u0010\u000e\u0010Ñ\u000b\u0010\u0003\u0011\u0003\u0011\u0003\u0011\u0007\u0011Ö\n\u0011\f\u0011\u000e\u0011Ù\u000b\u0011\u0003\u0012\u0003\u0012\u0003\u0012\u0003\u0012\u0003\u0012\u0003\u0012\u0003\u0012\u0003\u0012\u0003\u0012\u0003\u0012\u0005\u0012å\n\u0012\u0003\u0013\u0003\u0013\u0003\u0013\u0003\u0013\u0007\u0013ë\n\u0013\f\u0013\u000e\u0013î\u000b\u0013\u0003\u0013\u0003\u0013\u0003\u0014\u0003\u0014\u0003\u0015\u0003\u0015\u0003\u0015\u0003\u0015\u0003\u0015\u0007\u0015ù\n\u0015\f\u0015\u000e\u0015ü\u000b\u0015\u0003\u0015\u0003\u0015\u0003\u0015\u0003\u0016\u0003\u0016\u0003\u0017\u0003\u0017\u0003\u0017\u0007\u0017Ć\n\u0017\f\u0017\u000e\u0017ĉ\u000b\u0017\u0003\u0017\u0003\u0017\u0003\u0018\u0003\u0018\u0003\u0018\u0003\u0018\u0003\u0018\u0003\u0018\u0003\u0018\u0003\u0018\u0003\u0018\u0003\u0018\u0003\u0018\u0005\u0018Ę\n\u0018\u0003\u0019\u0006\u0019ě\n\u0019\r\u0019\u000e\u0019Ĝ\u0003\u0019\u0005\u0019Ġ\n\u0019\u0003\u001a\u0006\u001aģ\n\u001a\r\u001a\u000e\u001aĤ\u0003\u001b\u0003\u001b\u0003\u001b\u0002\u0002\u001c\u0002\u0004\u0006\b\n\f\u000e\u0010\u0012\u0014\u0016\u0018\u001a\u001c\u001e \"$&(*,.024\u0002\u0006\u0003\u0002\u0007\u000f\u0003\u0002'*\u0003\u0002+-\u0003\u0002.7\u0002ı\u00029\u0003\u0002\u0002\u0002\u0004B\u0003\u0002\u0002\u0002\u0006D\u0003\u0002\u0002\u0002\bN\u0003\u0002\u0002\u0002\nP\u0003\u0002\u0002\u0002\fZ\u0003\u0002\u0002\u0002\u000e^\u0003\u0002\u0002\u0002\u0010q\u0003\u0002\u0002\u0002\u0012~\u0003\u0002\u0002\u0002\u0014\u0080\u0003\u0002\u0002\u0002\u0016§\u0003\u0002\u0002\u0002\u0018»\u0003\u0002\u0002\u0002\u001a½\u0003\u0002\u0002\u0002\u001cÈ\u0003\u0002\u0002\u0002\u001eÊ\u0003\u0002\u0002\u0002 Ò\u0003\u0002\u0002\u0002\"ä\u0003\u0002\u0002\u0002$æ\u0003\u0002\u0002\u0002&ñ\u0003\u0002\u0002\u0002(ó\u0003\u0002\u0002\u0002*Ā\u0003\u0002\u0002\u0002,Ă\u0003\u0002\u0002\u0002.ė\u0003\u0002\u0002\u00020ğ\u0003\u0002\u0002\u00022Ģ\u0003\u0002\u0002\u00024Ħ\u0003\u0002\u0002\u000268\u0005\u0004\u0003\u000276\u0003\u0002\u0002\u00028;\u0003\u0002\u0002\u000297\u0003\u0002\u0002\u00029:\u0003\u0002\u0002\u0002:<\u0003\u0002\u0002\u0002;9\u0003\u0002\u0002\u0002<=\u0007\u0003\u0002\u0002=\u0003\u0003\u0002\u0002\u0002>C\u0005\u0006\u0004\u0002?C\u0005\n\u0006\u0002@C\u0005\u000e\b\u0002AC\u0005\u0012\n\u0002B>\u0003\u0002\u0002\u0002B?\u0003\u0002\u0002\u0002B@\u0003\u0002\u0002\u0002BA\u0003\u0002\u0002\u0002C\u0005\u0003\u0002\u0002\u0002DE\u0007\u0004\u0002\u0002EF\u0007\u0005\u0002\u0002FK\u0005\b\u0005\u0002GH\u0007\u0006\u0002\u0002HJ\u0005\b\u0005\u0002IG\u0003\u0002\u0002\u0002JM\u0003\u0002\u0002\u0002KI\u0003\u0002\u0002\u0002KL\u0003\u0002\u0002\u0002L\u0007\u0003\u0002\u0002\u0002MK\u0003\u0002\u0002\u0002NO\t\u0002\u0002\u0002O\t\u0003\u0002\u0002\u0002PQ\u0007\u0010\u0002\u0002QR\u0007\u0005\u0002\u0002RW\u0005\f\u0007\u0002ST\u0007\u0006\u0002\u0002TV\u0005\f\u0007\u0002US\u0003\u0002\u0002\u0002VY\u0003\u0002\u0002\u0002WU\u0003\u0002\u0002\u0002WX\u0003\u0002\u0002\u0002X\u000b\u0003\u0002\u0002\u0002YW\u0003\u0002\u0002\u0002Z[\u0005\"\u0012\u0002[\\\u0007\u0011\u0002\u0002\\]\u0005\"\u0012\u0002]\r\u0003\u0002\u0002\u0002^_\u0007\u0012\u0002\u0002_`\u0007\u0005\u0002\u0002`e\u0005\u0010\t\u0002ab\u0007\u0006\u0002\u0002bd\u0005\u0010\t\u0002ca\u0003\u0002\u0002\u0002dg\u0003\u0002\u0002\u0002ec\u0003\u0002\u0002\u0002ef\u0003\u0002\u0002\u0002f\u000f\u0003\u0002\u0002\u0002ge\u0003\u0002\u0002\u0002hi\u00050\u0019\u0002ij\u0007\u0013\u0002\u0002jk\u00052\u001a\u0002kr\u0003\u0002\u0002\u0002lm\u00050\u0019\u0002mn\u0007\u0013\u0002\u0002no\u00052\u001a\u0002op\u0007\u0014\u0002\u0002pr\u0003\u0002\u0002\u0002qh\u0003\u0002\u0002\u0002ql\u0003\u0002\u0002\u0002r\u0011\u0003\u0002\u0002\u0002st\u0007\u0015\u0002\u0002tu\u00050\u0019\u0002uv\u0007\u0005\u0002\u0002vw\u0005\u0016\f\u0002wx\u0005\u0014\u000b\u0002x\u007f\u0003\u0002\u0002\u0002yz\u0007\u0015\u0002\u0002z{\u00050\u0019\u0002{|\u0007\u0005\u0002\u0002|}\u0005\u0014\u000b\u0002}\u007f\u0003\u0002\u0002\u0002~s\u0003\u0002\u0002\u0002~y\u0003\u0002\u0002\u0002\u007f\u0013\u0003\u0002\u0002\u0002\u0080\u0081\u0007\u0016\u0002\u0002\u0081\u0086\u0005\u0018\r\u0002\u0082\u0083\u0007\u0006\u0002\u0002\u0083\u0085\u0005\u0018\r\u0002\u0084\u0082\u0003\u0002\u0002\u0002\u0085\u0088\u0003\u0002\u0002\u0002\u0086\u0084\u0003\u0002\u0002\u0002\u0086\u0087\u0003\u0002\u0002\u0002\u0087\u0089\u0003\u0002\u0002\u0002\u0088\u0086\u0003\u0002\u0002\u0002\u0089\u0096\u0007\u0017\u0002\u0002\u008a\u0097\u0007\u0018\u0002\u0002\u008b\u008c\u0007\u0019\u0002\u0002\u008c\u0091\u0005\u0018\r\u0002\u008d\u008e\u0007\u0006\u0002\u0002\u008e\u0090\u0005\u0018\r\u0002\u008f\u008d\u0003\u0002\u0002\u0002\u0090\u0093\u0003\u0002\u0002\u0002\u0091\u008f\u0003\u0002\u0002\u0002\u0091\u0092\u0003\u0002\u0002\u0002\u0092\u0094\u0003\u0002\u0002\u0002\u0093\u0091\u0003\u0002\u0002\u0002\u0094\u0095\u0007\u001a\u0002\u0002\u0095\u0097\u0003\u0002\u0002\u0002\u0096\u008a\u0003\u0002\u0002\u0002\u0096\u008b\u0003\u0002\u0002\u0002\u0097¥\u0003\u0002\u0002\u0002\u0098\u0099\u0007\u0016\u0002\u0002\u0099\u009e\u0005\u0018\r\u0002\u009a\u009b\u0007\u0006\u0002\u0002\u009b\u009d\u0005\u0018\r\u0002\u009c\u009a\u0003\u0002\u0002\u0002\u009d \u0003\u0002\u0002\u0002\u009e\u009c\u0003\u0002\u0002\u0002\u009e\u009f\u0003\u0002\u0002\u0002\u009f¡\u0003\u0002\u0002\u0002 \u009e\u0003\u0002\u0002\u0002¡¢\u0007\u0017\u0002\u0002¢¦\u0003\u0002\u0002\u0002£¤\u0007\u0016\u0002\u0002¤¦\u0007\u0017\u0002\u0002¥\u0098\u0003\u0002\u0002\u0002¥£\u0003\u0002\u0002\u0002¦\u0015\u0003\u0002\u0002\u0002§¬\u0007\u001b\u0002\u0002¨©\u00050\u0019\u0002©ª\u0007\u0011\u0002\u0002ª«\u0005\"\u0012\u0002«\u00ad\u0003\u0002\u0002\u0002¬¨\u0003\u0002\u0002\u0002\u00ad®\u0003\u0002\u0002\u0002®¬\u0003\u0002\u0002\u0002®¯\u0003\u0002\u0002\u0002¯°\u0003\u0002\u0002\u0002°±\u0007\u001c\u0002\u0002±\u0017\u0003\u0002\u0002\u0002²³\u0005\u001c\u000f\u0002³´\u0007\u001d\u0002\u0002´µ\u0005\u001a\u000e\u0002µ¶\u0007\u001e\u0002\u0002¶¼\u0003\u0002\u0002\u0002·¸\u0005\u001c\u000f\u0002¸¹\u0007\u001d\u0002\u0002¹º\u0007\u001e\u0002\u0002º¼\u0003\u0002\u0002\u0002»²\u0003\u0002\u0002\u0002»·\u0003\u0002\u0002\u0002¼\u0019\u0003\u0002\u0002\u0002½Â\u0005\u001e\u0010\u0002¾¿\u0007\u0006\u0002\u0002¿Á\u0005\u001e\u0010\u0002À¾\u0003\u0002\u0002\u0002ÁÄ\u0003\u0002\u0002\u0002ÂÀ\u0003\u0002\u0002\u0002ÂÃ\u0003\u0002\u0002\u0002Ã\u001b\u0003\u0002\u0002\u0002ÄÂ\u0003\u0002\u0002\u0002ÅÆ\u0007\u001f\u0002\u0002ÆÉ\u00050\u0019\u0002ÇÉ\u00050\u0019\u0002ÈÅ\u0003\u0002\u0002\u0002ÈÇ\u0003\u0002\u0002\u0002É\u001d\u0003\u0002\u0002\u0002ÊÏ\u0005 \u0011\u0002ËÌ\u0007 \u0002\u0002ÌÎ\u0005 \u0011\u0002ÍË\u0003\u0002\u0002\u0002ÎÑ\u0003\u0002\u0002\u0002ÏÍ\u0003\u0002\u0002\u0002ÏÐ\u0003\u0002\u0002\u0002Ð\u001f\u0003\u0002\u0002\u0002ÑÏ\u0003\u0002\u0002\u0002Ò×\u0005\"\u0012\u0002ÓÔ\u0007!\u0002\u0002ÔÖ\u0005\"\u0012\u0002ÕÓ\u0003\u0002\u0002\u0002ÖÙ\u0003\u0002\u0002\u0002×Õ\u0003\u0002\u0002\u0002×Ø\u0003\u0002\u0002\u0002Ø!\u0003\u0002\u0002\u0002Ù×\u0003\u0002\u0002\u0002Úå\u0005$\u0013\u0002ÛÜ\u0007\u001d\u0002\u0002ÜÝ\u0005\u001e\u0010\u0002ÝÞ\u0007\u001e\u0002\u0002Þå\u0003\u0002\u0002\u0002ßå\u0005&\u0014\u0002àå\u0005(\u0015\u0002áå\u0005,\u0017\u0002âå\u0005.\u0018\u0002ãå\u0005\u0018\r\u0002äÚ\u0003\u0002\u0002\u0002äÛ\u0003\u0002\u0002\u0002äß\u0003\u0002\u0002\u0002äà\u0003\u0002\u0002\u0002äá\u0003\u0002\u0002\u0002äâ\u0003\u0002\u0002\u0002äã\u0003\u0002\u0002\u0002å#\u0003\u0002\u0002\u0002æç\u0007\"\u0002\u0002çì\u0005\u001e\u0010\u0002èé\u0007\u0006\u0002\u0002éë\u0005\u001e\u0010\u0002êè\u0003\u0002\u0002\u0002ëî\u0003\u0002\u0002\u0002ìê\u0003\u0002\u0002\u0002ìí\u0003\u0002\u0002\u0002íï\u0003\u0002\u0002\u0002îì\u0003\u0002\u0002\u0002ïð\u0007#\u0002\u0002ð%\u0003\u0002\u0002\u0002ñò\u0007$\u0002\u0002ò'\u0003\u0002\u0002\u0002óô\u0005*\u0016\u0002ôõ\u0007%\u0002\u0002õú\u0005\u001e\u0010\u0002ö÷\u0007\u0006\u0002\u0002÷ù\u0005\u001e\u0010\u0002øö\u0003\u0002\u0002\u0002ùü\u0003\u0002\u0002\u0002úø\u0003\u0002\u0002\u0002úû\u0003\u0002\u0002\u0002ûý\u0003\u0002\u0002\u0002üú\u0003\u0002\u0002\u0002ýþ\u0007&\u0002\u0002þÿ\u0005\"\u0012\u0002ÿ)\u0003\u0002\u0002\u0002Āā\t\u0003\u0002\u0002ā+\u0003\u0002\u0002\u0002Ăă\u0005*\u0016\u0002ăć\u0007\u001d\u0002\u0002ĄĆ\u0005\u001e\u0010\u0002ąĄ\u0003\u0002\u0002\u0002Ćĉ\u0003\u0002\u0002\u0002ćą\u0003\u0002\u0002\u0002ćĈ\u0003\u0002\u0002\u0002ĈĊ\u0003\u0002\u0002\u0002ĉć\u0003\u0002\u0002\u0002Ċċ\u0007\u001e\u0002\u0002ċ-\u0003\u0002\u0002\u0002Čč\u00079\u0002\u0002čĎ\u00050\u0019\u0002Ďď\u00079\u0002\u0002ďĘ\u0003\u0002\u0002\u0002Đđ\t\u0004\u0002\u0002đĘ\u00050\u0019\u0002Ēē\u0007:\u0002\u0002ēĔ\u00050\u0019\u0002Ĕĕ\u00079\u0002\u0002ĕĘ\u0003\u0002\u0002\u0002ĖĘ\u00050\u0019\u0002ėČ\u0003\u0002\u0002\u0002ėĐ\u0003\u0002\u0002\u0002ėĒ\u0003\u0002\u0002\u0002ėĖ\u0003\u0002\u0002\u0002Ę/\u0003\u0002\u0002\u0002ęě\u00078\u0002\u0002Ěę\u0003\u0002\u0002\u0002ěĜ\u0003\u0002\u0002\u0002ĜĚ\u0003\u0002\u0002\u0002Ĝĝ\u0003\u0002\u0002\u0002ĝĠ\u0003\u0002\u0002\u0002ĞĠ\u00054\u001b\u0002ğĚ\u0003\u0002\u0002\u0002ğĞ\u0003\u0002\u0002\u0002Ġ1\u0003\u0002\u0002\u0002ġģ\u00054\u001b\u0002Ģġ\u0003\u0002\u0002\u0002ģĤ\u0003\u0002\u0002\u0002ĤĢ\u0003\u0002\u0002\u0002Ĥĥ\u0003\u0002\u0002\u0002ĥ3\u0003\u0002\u0002\u0002Ħħ\t\u0005\u0002\u0002ħ5\u0003\u0002\u0002\u0002\u001c9BKWeq~\u0086\u0091\u0096\u009e¥®»ÂÈÏ×äìúćėĜğĤ";
  }

  /**
   * Get ATN (Abstract Syntax Tree) for the lexer.
   *
   * @return the ATN instance used by the lexer
   */
  public ATN getATN() {
    return _ATN;
  }

  /**
   * Constructor for the TamarinParser.
   *
   * @param input the input token stream
   */
  public TamarinParser(TokenStream input) {
    super(input);
    this._interp = new ParserATNSimulator(this, _ATN, _decisionToDFA, _sharedContextCache);
  }

  /**
   * The entry point for parsing a Tamarin theory.
   *
   * @return the context of the parsed theory
   * @throws RecognitionException if there is a parsing error
   */
  public final TheoryContext theory() throws RecognitionException {
    TheoryContext _localctx = new TheoryContext(this._ctx, this.getState());
    this.enterRule(_localctx, 0, 0);

    try {
      this.enterOuterAlt(_localctx, 1);
      this.setState(55);
      this._errHandler.sync(this);

      for (int _la = this._input.LA(1);
          (_la & -64) == 0 && (1L << _la & 606212L) != 0L;
          _la = this._input.LA(1)) {
        this.setState(52);
        this.component();
        this.setState(57);
        this._errHandler.sync(this);
      }

      this.setState(58);
      this.match(1);
    } catch (RecognitionException var7) {
      RecognitionException re = var7;
      _localctx.exception = re;
      this._errHandler.reportError(this, re);
      this._errHandler.recover(this, re);
    } finally {
      this.exitRule();
    }

    return _localctx;
  }

  /**
   * The entry point for parsing a component in Tamarin.
   *
   * @return the context of the parsed component
   * @throws RecognitionException if there is a parsing error
   */
  public final ComponentContext component() throws RecognitionException {
    ComponentContext _localctx = new ComponentContext(this._ctx, this.getState());
    this.enterRule(_localctx, 2, 1);

    try {
      this.setState(64);
      this._errHandler.sync(this);
      switch (this._input.LA(1)) {
        case 2:
          this.enterOuterAlt(_localctx, 1);
          this.setState(60);
          this.built_in();
          break;
        case 14:
          this.enterOuterAlt(_localctx, 2);
          this.setState(61);
          this.equations();
          break;
        case 16:
          this.enterOuterAlt(_localctx, 3);
          this.setState(62);
          this.functions();
          break;
        case 19:
          this.enterOuterAlt(_localctx, 4);
          this.setState(63);
          this.protocolrule();
          break;
        default:
          throw new NoViableAltException(this);
      }
    } catch (RecognitionException var6) {
      RecognitionException re = var6;
      _localctx.exception = re;
      this._errHandler.reportError(this, re);
      this._errHandler.recover(this, re);
    } finally {
      this.exitRule();
    }

    return _localctx;
  }

  /**
   * The entry point for parsing a built-in component in Tamarin.
   *
   * @return the context of the parsed built-in component
   * @throws RecognitionException if there is a parsing error
   */
  public final Built_inContext built_in() throws RecognitionException {
    Built_inContext _localctx = new Built_inContext(this._ctx, this.getState());
    this.enterRule(_localctx, 4, 2);

    try {
      this.enterOuterAlt(_localctx, 1);
      this.setState(66);
      this.match(2);
      this.setState(67);
      this.match(3);
      this.setState(68);
      this.builtin_name();
      this.setState(73);
      this._errHandler.sync(this);

      for (int _la = this._input.LA(1); _la == 4; _la = this._input.LA(1)) {
        this.setState(69);
        this.match(4);
        this.setState(70);
        this.builtin_name();
        this.setState(75);
        this._errHandler.sync(this);
      }
    } catch (RecognitionException var7) {
      RecognitionException re = var7;
      _localctx.exception = re;
      this._errHandler.reportError(this, re);
      this._errHandler.recover(this, re);
    } finally {
      this.exitRule();
    }

    return _localctx;
  }

  /**
   * The entry point for parsing a built-in name in Tamarin.
   *
   * @return the context of the parsed built-in name
   * @throws RecognitionException if there is a parsing error
   */
  public final Builtin_nameContext builtin_name() throws RecognitionException {
    Builtin_nameContext _localctx = new Builtin_nameContext(this._ctx, this.getState());
    this.enterRule(_localctx, 6, 3);

    try {
      this.enterOuterAlt(_localctx, 1);
      this.setState(76);
      int _la = this._input.LA(1);
      if ((_la & -64) == 0 && (1L << _la & 16352L) != 0L) {
        if (this._input.LA(1) == -1) {
          this.matchedEOF = true;
        }

        this._errHandler.reportMatch(this);
        this.consume();
      } else {
        this._errHandler.recoverInline(this);
      }
    } catch (RecognitionException var7) {
      RecognitionException re = var7;
      _localctx.exception = re;
      this._errHandler.reportError(this, re);
      this._errHandler.recover(this, re);
    } finally {
      this.exitRule();
    }

    return _localctx;
  }

  /**
   * The entry point for parsing equations in Tamarin.
   *
   * @return the context of the parsed equations
   * @throws RecognitionException if there is a parsing error
   */
  public final EquationsContext equations() throws RecognitionException {
    EquationsContext _localctx = new EquationsContext(this._ctx, this.getState());
    this.enterRule(_localctx, 8, 4);

    try {
      this.enterOuterAlt(_localctx, 1);
      this.setState(78);
      this.match(14);
      this.setState(79);
      this.match(3);
      this.setState(80);
      this.equation_symbol();
      this.setState(85);
      this._errHandler.sync(this);

      for (int _la = this._input.LA(1); _la == 4; _la = this._input.LA(1)) {
        this.setState(81);
        this.match(4);
        this.setState(82);
        this.equation_symbol();
        this.setState(87);
        this._errHandler.sync(this);
      }
    } catch (RecognitionException var7) {
      RecognitionException re = var7;
      _localctx.exception = re;
      this._errHandler.reportError(this, re);
      this._errHandler.recover(this, re);
    } finally {
      this.exitRule();
    }

    return _localctx;
  }

  /**
   * Parses an equation symbol in Tamarin.
   *
   * @return the context of the parsed equation symbol
   * @throws RecognitionException if there is a parsing error
   */
  public final Equation_symbolContext equation_symbol() throws RecognitionException {
    Equation_symbolContext _localctx = new Equation_symbolContext(this._ctx, this.getState());
    this.enterRule(_localctx, 10, 5);

    try {
      this.enterOuterAlt(_localctx, 1);
      this.setState(88);
      this.term();
      this.setState(89);
      this.match(15);
      this.setState(90);
      this.term();
    } catch (RecognitionException var6) {
      RecognitionException re = var6;
      _localctx.exception = re;
      this._errHandler.reportError(this, re);
      this._errHandler.recover(this, re);
    } finally {
      this.exitRule();
    }

    return _localctx;
  }

  /**
   * Parses a list of functions in Tamarin.
   *
   * @return the context of the parsed functions
   * @throws RecognitionException if there is a parsing error
   */
  public final FunctionsContext functions() throws RecognitionException {
    FunctionsContext _localctx = new FunctionsContext(this._ctx, this.getState());
    this.enterRule(_localctx, 12, 6);

    try {
      this.enterOuterAlt(_localctx, 1);
      this.setState(92);
      this.match(16);
      this.setState(93);
      this.match(3);
      this.setState(94);
      this.function_symbol();
      this.setState(99);
      this._errHandler.sync(this);

      for (int _la = this._input.LA(1); _la == 4; _la = this._input.LA(1)) {
        this.setState(95);
        this.match(4);
        this.setState(96);
        this.function_symbol();
        this.setState(101);
        this._errHandler.sync(this);
      }
    } catch (RecognitionException var7) {
      RecognitionException re = var7;
      _localctx.exception = re;
      this._errHandler.reportError(this, re);
      this._errHandler.recover(this, re);
    } finally {
      this.exitRule();
    }

    return _localctx;
  }

  /**
   * Parses a function symbol in Tamarin.
   *
   * @return the context of the parsed function symbol
   * @throws RecognitionException if there is a parsing error
   */
  public final Function_symbolContext function_symbol() throws RecognitionException {
    Function_symbolContext _localctx = new Function_symbolContext(this._ctx, this.getState());
    this.enterRule(_localctx, 14, 7);

    try {
      this.setState(111);
      this._errHandler.sync(this);
      switch (this.getInterpreter()
          .adaptivePredict(this._input, 5, this._ctx)) {
        case 1:
          this.enterOuterAlt(_localctx, 1);
          this.setState(102);
          this.identifier();
          this.setState(103);
          this.match(17);
          this.setState(104);
          this.natural();
          break;
        case 2:
          this.enterOuterAlt(_localctx, 2);
          this.setState(106);
          this.identifier();
          this.setState(107);
          this.match(17);
          this.setState(108);
          this.natural();
          this.setState(109);
          this.match(18);
      }
    } catch (RecognitionException var6) {
      RecognitionException re = var6;
      _localctx.exception = re;
      this._errHandler.reportError(this, re);
      this._errHandler.recover(this, re);
    } finally {
      this.exitRule();
    }

    return _localctx;
  }

  /**
   * Parses a protocol rule in Tamarin.
   *
   * @return the context of the parsed protocol rule
   * @throws RecognitionException if there is a parsing error
   */
  public final ProtocolruleContext protocolrule() throws RecognitionException {
    ProtocolruleContext _localctx = new ProtocolruleContext(this._ctx, this.getState());
    this.enterRule(_localctx, 16, 8);

    try {
      this.setState(124);
      this._errHandler.sync(this);
      switch (this.getInterpreter()
          .adaptivePredict(this._input, 6, this._ctx)) {
        case 1:
          this.enterOuterAlt(_localctx, 1);
          this.setState(113);
          this.match(19);
          this.setState(114);
          this.identifier();
          this.setState(115);
          this.match(3);
          this.setState(116);
          this.let_block();
          this.setState(117);
          this.genericrule();
          break;
        case 2:
          this.enterOuterAlt(_localctx, 2);
          this.setState(119);
          this.match(19);
          this.setState(120);
          this.identifier();
          this.setState(121);
          this.match(3);
          this.setState(122);
          this.genericrule();
      }
    } catch (RecognitionException var6) {
      RecognitionException re = var6;
      _localctx.exception = re;
      this._errHandler.reportError(this, re);
      this._errHandler.recover(this, re);
    } finally {
      this.exitRule();
    }

    return _localctx;
  }

  /**
   * Parses a generic rule in Tamarin.
   *
   * @return the context of the parsed generic rule
   * @throws RecognitionException if there is a parsing error
   */
  public final GenericruleContext genericrule() throws RecognitionException {
    GenericruleContext _localctx = new GenericruleContext(this._ctx, this.getState());
    this.enterRule(_localctx, 18, 9);

    try {
      this.enterOuterAlt(_localctx, 1);
      this.setState(126);
      this.match(20);
      this.setState(127);
      this._errHandler.sync(this);
      int _la = this._input.LA(1);
      if (_la != 21) {
        this.fact();
        this.setState(132);
        this._errHandler.sync(this);

        for (_la = this._input.LA(1); _la == 4; _la = this._input.LA(1)) {
          this.setState(128);
          this.match(4);
          this.setState(129);
          this.fact();
          this.setState(134);
          this._errHandler.sync(this);
        }
      }

      this.setState(135);
      this.match(21);
      this.setState(148);
      this._errHandler.sync(this);
      switch (this._input.LA(1)) {
        case 22:
          this.setState(136);
          this.match(22);
          break;
        case 23:
          this.setState(137);
          this.match(23);
          this.setState(138);
          this.fact();
          this.setState(143);
          this._errHandler.sync(this);

          for (_la = this._input.LA(1); _la == 4; _la = this._input.LA(1)) {
            this.setState(139);
            this.match(4);
            this.setState(140);
            this.fact();
            this.setState(145);
            this._errHandler.sync(this);
          }

          this.setState(146);
          this.match(24);
          break;
        default:
          throw new NoViableAltException(this);
      }

      this.setState(163);
      this._errHandler.sync(this);
      switch (this.getInterpreter()
          .adaptivePredict(this._input, 11, this._ctx)) {
        case 1:
          this.setState(150);
          this.match(20);
          this.setState(151);
          this.fact();
          this.setState(156);
          this._errHandler.sync(this);

          for (_la = this._input.LA(1); _la == 4; _la = this._input.LA(1)) {
            this.setState(152);
            this.match(4);
            this.setState(153);
            this.fact();
            this.setState(158);
            this._errHandler.sync(this);
          }

          this.setState(159);
          this.match(21);
          break;
        case 2:
          this.setState(161);
          this.match(20);
          this.setState(162);
          this.match(21);
      }
    } catch (RecognitionException var7) {
      RecognitionException re = var7;
      _localctx.exception = re;
      this._errHandler.reportError(this, re);
      this._errHandler.recover(this, re);
    } finally {
      this.exitRule();
    }

    return _localctx;
  }

  /**
   * Parses a let block in Tamarin.
   *
   * @return the context of the parsed let block
   * @throws RecognitionException if there is a parsing error
   */
  public final Let_blockContext let_block() throws RecognitionException {
    Let_blockContext _localctx = new Let_blockContext(this._ctx, this.getState());
    this.enterRule(_localctx, 20, 10);

    try {
      this.enterOuterAlt(_localctx, 1);
      this.setState(165);
      this.match(25);
      this.setState(170);
      this._errHandler.sync(this);
      int _la = this._input.LA(1);

      do {
        this.setState(166);
        this.identifier();
        this.setState(167);
        this.match(15);
        this.setState(168);
        this.term();
        this.setState(172);
        this._errHandler.sync(this);
        _la = this._input.LA(1);
      } while ((_la & -64) == 0 && (1L << _la & 36011204832919552L) != 0L);

      this.setState(174);
      this.match(26);
    } catch (RecognitionException var7) {
      RecognitionException re = var7;
      _localctx.exception = re;
      this._errHandler.reportError(this, re);
      this._errHandler.recover(this, re);
    } finally {
      this.exitRule();
    }

    return _localctx;
  }

  /**
   * Parses a fact in Tamarin.
   *
   * @return the context of the parsed fact
   * @throws RecognitionException if there is a parsing error
   */
  public final FactContext fact() throws RecognitionException {
    FactContext _localctx = new FactContext(this._ctx, this.getState());
    this.enterRule(_localctx, 22, 11);

    try {
      this.setState(185);
      this._errHandler.sync(this);
      switch (this.getInterpreter()
          .adaptivePredict(this._input, 13, this._ctx)) {
        case 1:
          this.enterOuterAlt(_localctx, 1);
          this.setState(176);
          this.fact_identifier();
          this.setState(177);
          this.match(27);
          this.setState(178);
          this.terms();
          this.setState(179);
          this.match(28);
          break;
        case 2:
          this.enterOuterAlt(_localctx, 2);
          this.setState(181);
          this.fact_identifier();
          this.setState(182);
          this.match(27);
          this.setState(183);
          this.match(28);
      }
    } catch (RecognitionException var6) {
      RecognitionException re = var6;
      _localctx.exception = re;
      this._errHandler.reportError(this, re);
      this._errHandler.recover(this, re);
    } finally {
      this.exitRule();
    }

    return _localctx;
  }

  /**
   * Parses a list of terms in Tamarin.
   *
   * @return the context of the parsed terms
   * @throws RecognitionException if there is a parsing error
   */
  public final TermsContext terms() throws RecognitionException {
    TermsContext _localctx = new TermsContext(this._ctx, this.getState());
    this.enterRule(_localctx, 24, 12);

    try {
      this.enterOuterAlt(_localctx, 1);
      this.setState(187);
      this.multterm();
      this.setState(192);
      this._errHandler.sync(this);

      for (int _la = this._input.LA(1); _la == 4; _la = this._input.LA(1)) {
        this.setState(188);
        this.match(4);
        this.setState(189);
        this.multterm();
        this.setState(194);
        this._errHandler.sync(this);
      }
    } catch (RecognitionException var7) {
      RecognitionException re = var7;
      _localctx.exception = re;
      this._errHandler.reportError(this, re);
      this._errHandler.recover(this, re);
    } finally {
      this.exitRule();
    }

    return _localctx;
  }

  /**
   * Parses a fact identifier in Tamarin.
   *
   * @return the context of the parsed fact identifier
   * @throws RecognitionException if there is a parsing error
   */
  public final Fact_identifierContext fact_identifier() throws RecognitionException {
    Fact_identifierContext _localctx = new Fact_identifierContext(this._ctx, this.getState());
    this.enterRule(_localctx, 26, 13);

    try {
      this.setState(198);
      this._errHandler.sync(this);
      switch (this._input.LA(1)) {
        case 29:
          this.enterOuterAlt(_localctx, 1);
          this.setState(195);
          this.match(29);
          this.setState(196);
          this.identifier();
          break;
        case 30:
        case 31:
        case 32:
        case 33:
        case 34:
        case 35:
        case 36:
        case 37:
        case 38:
        case 39:
        case 40:
        case 41:
        case 42:
        case 43:
        default:
          throw new NoViableAltException(this);
        case 44:
        case 45:
        case 46:
        case 47:
        case 48:
        case 49:
        case 50:
        case 51:
        case 52:
        case 53:
        case 54:
          this.enterOuterAlt(_localctx, 2);
          this.setState(197);
          this.identifier();
      }
    } catch (RecognitionException var6) {
      RecognitionException re = var6;
      _localctx.exception = re;
      this._errHandler.reportError(this, re);
      this._errHandler.recover(this, re);
    } finally {
      this.exitRule();
    }

    return _localctx;
  }

  /**
   * Parses a multterm in Tamarin.
   *
   * @return the context of the parsed multterm
   * @throws RecognitionException if there is a parsing error
   */
  public final MulttermContext multterm() throws RecognitionException {
    MulttermContext _localctx = new MulttermContext(this._ctx, this.getState());
    this.enterRule(_localctx, 28, 14);

    try {
      this.enterOuterAlt(_localctx, 1);
      this.setState(200);
      this.expterm();
      this.setState(205);
      this._errHandler.sync(this);

      for (int _la = this._input.LA(1); _la == 30; _la = this._input.LA(1)) {
        this.setState(201);
        this.match(30);
        this.setState(202);
        this.expterm();
        this.setState(207);
        this._errHandler.sync(this);
      }
    } catch (RecognitionException var7) {
      RecognitionException re = var7;
      _localctx.exception = re;
      this._errHandler.reportError(this, re);
      this._errHandler.recover(this, re);
    } finally {
      this.exitRule();
    }

    return _localctx;
  }

  /**
   * Parses an expterm in Tamarin.
   *
   * @return the context of the parsed expterm
   * @throws RecognitionException if there is a parsing error
   */
  public final ExptermContext expterm() throws RecognitionException {
    ExptermContext _localctx = new ExptermContext(this._ctx, this.getState());
    this.enterRule(_localctx, 30, 15);

    try {
      this.enterOuterAlt(_localctx, 1);
      this.setState(208);
      this.term();
      this.setState(213);
      this._errHandler.sync(this);

      for (int _la = this._input.LA(1); _la == 31; _la = this._input.LA(1)) {
        this.setState(209);
        this.match(31);
        this.setState(210);
        this.term();
        this.setState(215);
        this._errHandler.sync(this);
      }
    } catch (RecognitionException var7) {
      RecognitionException re = var7;
      _localctx.exception = re;
      this._errHandler.reportError(this, re);
      this._errHandler.recover(this, re);
    } finally {
      this.exitRule();
    }

    return _localctx;
  }

  /**
   * Parses a term in Tamarin.
   *
   * @return the context of the parsed term
   * @throws RecognitionException if there is a parsing error
   */
  public final TermContext term() throws RecognitionException {
    TermContext _localctx = new TermContext(this._ctx, this.getState());
    this.enterRule(_localctx, 32, 16);

    try {
      this.setState(226);
      this._errHandler.sync(this);
      switch (this.getInterpreter()
          .adaptivePredict(this._input, 18, this._ctx)) {
        case 1:
          this.enterOuterAlt(_localctx, 1);
          this.setState(216);
          this.group_of_terms();
          break;
        case 2:
          this.enterOuterAlt(_localctx, 2);
          this.setState(217);
          this.match(27);
          this.setState(218);
          this.multterm();
          this.setState(219);
          this.match(28);
          break;
        case 3:
          this.enterOuterAlt(_localctx, 3);
          this.setState(221);
          this.nullary_fun();
          break;
        case 4:
          this.enterOuterAlt(_localctx, 4);
          this.setState(222);
          this.binary_app();
          break;
        case 5:
          this.enterOuterAlt(_localctx, 5);
          this.setState(223);
          this.nary_app();
          break;
        case 6:
          this.enterOuterAlt(_localctx, 6);
          this.setState(224);
          this.literal();
          break;
        case 7:
          this.enterOuterAlt(_localctx, 7);
          this.setState(225);
          this.fact();
      }
    } catch (RecognitionException var6) {
      RecognitionException re = var6;
      _localctx.exception = re;
      this._errHandler.reportError(this, re);
      this._errHandler.recover(this, re);
    } finally {
      this.exitRule();
    }

    return _localctx;
  }

  /**
   * Parses a group of terms in Tamarin.
   *
   * @return the context of the parsed group of terms
   * @throws RecognitionException if there is a parsing error
   */
  public final Group_of_termsContext group_of_terms() throws RecognitionException {
    Group_of_termsContext _localctx = new Group_of_termsContext(this._ctx, this.getState());
    this.enterRule(_localctx, 34, 17);

    try {
      this.enterOuterAlt(_localctx, 1);
      this.setState(228);
      this.match(32);
      this.setState(229);
      this.multterm();
      this.setState(234);
      this._errHandler.sync(this);

      for (int _la = this._input.LA(1); _la == 4; _la = this._input.LA(1)) {
        this.setState(230);
        this.match(4);
        this.setState(231);
        this.multterm();
        this.setState(236);
        this._errHandler.sync(this);
      }

      this.setState(237);
      this.match(33);
    } catch (RecognitionException var7) {
      RecognitionException re = var7;
      _localctx.exception = re;
      this._errHandler.reportError(this, re);
      this._errHandler.recover(this, re);
    } finally {
      this.exitRule();
    }

    return _localctx;
  }

  /**
   * Parses a nullary function in Tamarin.
   *
   * @return the context of the parsed nullary function
   * @throws RecognitionException if there is a parsing error
   */
  public final Nullary_funContext nullary_fun() throws RecognitionException {
    Nullary_funContext _localctx = new Nullary_funContext(this._ctx, this.getState());
    this.enterRule(_localctx, 36, 18);

    try {
      this.enterOuterAlt(_localctx, 1);
      this.setState(239);
      this.match(34);
    } catch (RecognitionException var6) {
      RecognitionException re = var6;
      _localctx.exception = re;
      this._errHandler.reportError(this, re);
      this._errHandler.recover(this, re);
    } finally {
      this.exitRule();
    }

    return _localctx;
  }

  /**
   * Parses a binary application in Tamarin.
   *
   * @return the context of the parsed binary application
   * @throws RecognitionException if there is a parsing error
   */
  public final Binary_appContext binary_app() throws RecognitionException {
    Binary_appContext _localctx = new Binary_appContext(this._ctx, this.getState());
    this.enterRule(_localctx, 38, 19);

    try {
      this.enterOuterAlt(_localctx, 1);
      this.setState(241);
      this.binary_fun();
      this.setState(242);
      this.match(35);
      this.setState(243);
      this.multterm();
      this.setState(248);
      this._errHandler.sync(this);

      for (int _la = this._input.LA(1); _la == 4; _la = this._input.LA(1)) {
        this.setState(244);
        this.match(4);
        this.setState(245);
        this.multterm();
        this.setState(250);
        this._errHandler.sync(this);
      }

      this.setState(251);
      this.match(36);
      this.setState(252);
      this.term();
    } catch (RecognitionException var7) {
      RecognitionException re = var7;
      _localctx.exception = re;
      this._errHandler.reportError(this, re);
      this._errHandler.recover(this, re);
    } finally {
      this.exitRule();
    }

    return _localctx;
  }

  /**
   * Parses a binary function in Tamarin.
   *
   * @return the context of the parsed binary function
   * @throws RecognitionException if there is a parsing error
   */
  public final Binary_funContext binary_fun() throws RecognitionException {
    Binary_funContext _localctx = new Binary_funContext(this._ctx, this.getState());
    this.enterRule(_localctx, 40, 20);

    try {
      this.enterOuterAlt(_localctx, 1);
      this.setState(254);
      int _la = this._input.LA(1);
      if ((_la & -64) == 0 && (1L << _la & 2061584302080L) != 0L) {
        if (this._input.LA(1) == -1) {
          this.matchedEOF = true;
        }

        this._errHandler.reportMatch(this);
        this.consume();
      } else {
        this._errHandler.recoverInline(this);
      }
    } catch (RecognitionException var7) {
      RecognitionException re = var7;
      _localctx.exception = re;
      this._errHandler.reportError(this, re);
      this._errHandler.recover(this, re);
    } finally {
      this.exitRule();
    }

    return _localctx;
  }

  /**
   * Parses an n-ary application in Tamarin.
   * Modified to support comma-separated arguments like senc(m1,m2).
   * Grammar: nary_app : binary_fun '(' (multterm (',' multterm)*)? ')';
   *
   * @return the context of the parsed n-ary application
   * @throws RecognitionException if there is a parsing error
   */
  public final Nary_appContext nary_app() throws RecognitionException {
    Nary_appContext _localctx = new Nary_appContext(this._ctx, this.getState());
    this.enterRule(_localctx, 42, 21);

    try {
      this.enterOuterAlt(_localctx, 1);
      this.setState(256);
      this.binary_fun();
      this.setState(257);
      this.match(27); // '('

      // Check if there are arguments (not immediately ')')
      int _la = this._input.LA(1);
      // Token bitmask for valid term starters: includes '<', ALPHA, SQUOTE, '$', '~', '#', digits, aenc/sign/pk/senc, '(', '!', 'all'
      if (_la != 28) { // Not ')'
        this.multterm();
        this._errHandler.sync(this);

        // Handle comma-separated arguments: (',' multterm)*
        while (this._input.LA(1) == 4) { // 4 is ','
          this.match(4); // consume ','
          this.multterm();
          this._errHandler.sync(this);
        }
      }

      this.match(28); // ')'
    } catch (RecognitionException var7) {
      RecognitionException re = var7;
      _localctx.exception = re;
      this._errHandler.reportError(this, re);
      this._errHandler.recover(this, re);
    } finally {
      this.exitRule();
    }

    return _localctx;
  }

  /**
   * Parses a literal in Tamarin.
   *
   * @return the context of the parsed literal
   * @throws RecognitionException if there is a parsing error
   */
  public final LiteralContext literal() throws RecognitionException {
    LiteralContext _localctx = new LiteralContext(this._ctx, this.getState());
    this.enterRule(_localctx, 44, 22);

    try {
      this.setState(277);
      this._errHandler.sync(this);
      switch (this._input.LA(1)) {
        case 41:
        case 42:
        case 43:
          this.enterOuterAlt(_localctx, 2);
          this.setState(270);
          int _la = this._input.LA(1);
          if ((_la & -64) == 0 && (1L << _la & 15393162788864L) != 0L) {
            if (this._input.LA(1) == -1) {
              this.matchedEOF = true;
            }

            this._errHandler.reportMatch(this);
            this.consume();
          } else {
            this._errHandler.recoverInline(this);
          }

          this.setState(271);
          this.identifier();
          break;
        case 44:
        case 45:
        case 46:
        case 47:
        case 48:
        case 49:
        case 50:
        case 51:
        case 52:
        case 53:
        case 54:
          this.enterOuterAlt(_localctx, 4);
          this.setState(276);
          this.identifier();
          break;
        case 55:
          this.enterOuterAlt(_localctx, 1);
          this.setState(266);
          this.match(55);
          this.setState(267);
          this.identifier();
          this.setState(268);
          this.match(55);
          break;
        case 56:
          this.enterOuterAlt(_localctx, 3);
          this.setState(272);
          this.match(56);
          this.setState(273);
          this.identifier();
          this.setState(274);
          this.match(55);
          break;
        default:
          throw new NoViableAltException(this);
      }
    } catch (RecognitionException var7) {
      RecognitionException re = var7;
      _localctx.exception = re;
      this._errHandler.reportError(this, re);
      this._errHandler.recover(this, re);
    } finally {
      this.exitRule();
    }

    return _localctx;
  }

  /**
   * Parses an identifier in Tamarin.
   *
   * @return the context of the parsed identifier
   * @throws RecognitionException if there is a parsing error
   */
  public final IdentifierContext identifier() throws RecognitionException {
    IdentifierContext _localctx = new IdentifierContext(this._ctx, this.getState());
    this.enterRule(_localctx, 46, 23);

    try {
      this.setState(286);
      this._errHandler.sync(this);
      switch (this._input.LA(1)) {
        case 44:
        case 45:
        case 46:
        case 47:
        case 48:
        case 49:
        case 50:
        case 51:
        case 52:
        case 53:
          this.enterOuterAlt(_localctx, 2);
          this.setState(285);
          this.digit();
          break;
        case 54:
          this.enterOuterAlt(_localctx, 1);
          this.setState(280);
          this._errHandler.sync(this);
          int _alt = 1;

          do {
            switch (_alt) {
              case 1:
                this.setState(279);
                this.match(54);
                break;
              default:
                throw new NoViableAltException(this);
            }

            this.setState(282);
            this._errHandler.sync(this);
            _alt = this.getInterpreter().adaptivePredict(this._input, 25, this._ctx);
          } while (_alt != 2 && _alt != 0);

          break;
        default:
          throw new NoViableAltException(this);
      }
    } catch (RecognitionException var6) {
      RecognitionException re = var6;
      _localctx.exception = re;
      this._errHandler.reportError(this, re);
      this._errHandler.recover(this, re);
    } finally {
      this.exitRule();
    }

    return _localctx;
  }

  /**
   * Parses a natural number in Tamarin.
   *
   * @return the context of the parsed natural number
   * @throws RecognitionException if there is a parsing error
   */
  public final NaturalContext natural() throws RecognitionException {
    NaturalContext _localctx = new NaturalContext(this._ctx, this.getState());
    this.enterRule(_localctx, 48, 24);

    try {
      this.enterOuterAlt(_localctx, 1);
      this.setState(288);
      this._errHandler.sync(this);
      int _la = this._input.LA(1);

      do {
        this.setState(287);
        this.digit();
        this.setState(290);
        this._errHandler.sync(this);
        _la = this._input.LA(1);
      } while ((_la & -64) == 0 && (1L << _la & 17996806323437568L) != 0L);
    } catch (RecognitionException var7) {
      RecognitionException re = var7;
      _localctx.exception = re;
      this._errHandler.reportError(this, re);
      this._errHandler.recover(this, re);
    } finally {
      this.exitRule();
    }

    return _localctx;
  }

  /**
   * Parses a digit in Tamarin.
   *
   * @return the context of the parsed digit
   * @throws RecognitionException if there is a parsing error
   */
  public final DigitContext digit() throws RecognitionException {
    DigitContext _localctx = new DigitContext(this._ctx, this.getState());
    this.enterRule(_localctx, 50, 25);

    try {
      this.enterOuterAlt(_localctx, 1);
      this.setState(292);
      int _la = this._input.LA(1);
      if ((_la & -64) == 0 && (1L << _la & 17996806323437568L) != 0L) {
        if (this._input.LA(1) == -1) {
          this.matchedEOF = true;
        }

        this._errHandler.reportMatch(this);
        this.consume();
      } else {
        this._errHandler.recoverInline(this);
      }
    } catch (RecognitionException var7) {
      RecognitionException re = var7;
      _localctx.exception = re;
      this._errHandler.reportError(this, re);
      this._errHandler.recover(this, re);
    } finally {
      this.exitRule();
    }

    return _localctx;
  }

  static {
    RuntimeMetaData.checkVersion("4.7.2", "4.7.2");
    _sharedContextCache = new PredictionContextCache();
    ruleNames = makeRuleNames();
    _LITERAL_NAMES = makeLiteralNames();
    _SYMBOLIC_NAMES = makeSymbolicNames();
    VOCABULARY = new VocabularyImpl(_LITERAL_NAMES, _SYMBOLIC_NAMES);
    tokenNames = new String[_SYMBOLIC_NAMES.length];

    int i;
    for (i = 0; i < tokenNames.length; ++i) {
      tokenNames[i] = VOCABULARY.getLiteralName(i);
      if (tokenNames[i] == null) {
        tokenNames[i] = VOCABULARY.getSymbolicName(i);
      }

      if (tokenNames[i] == null) {
        tokenNames[i] = "<INVALID>";
      }
    }

    _ATN =
        (new ATNDeserializer())
            .deserialize(
                "\u0003悋Ꜫ脳맭䅼㯧瞆奤\u0003=ĩ\u0004\u0002\t\u0002\u0004\u0003\t\u0003\u0004\u0004\t\u0004\u0004\u0005\t\u0005\u0004\u0006\t\u0006\u0004\u0007\t\u0007\u0004\b\t\b\u0004\t\t\t\u0004\n\t\n\u0004\u000b\t\u000b\u0004\f\t\f\u0004\r\t\r\u0004\u000e\t\u000e\u0004\u000f\t\u000f\u0004\u0010\t\u0010\u0004\u0011\t\u0011\u0004\u0012\t\u0012\u0004\u0013\t\u0013\u0004\u0014\t\u0014\u0004\u0015\t\u0015\u0004\u0016\t\u0016\u0004\u0017\t\u0017\u0004\u0018\t\u0018\u0004\u0019\t\u0019\u0004\u001a\t\u001a\u0004\u001b\t\u001b\u0003\u0002\u0007\u00028\n\u0002\f\u0002\u000e\u0002;\u000b\u0002\u0003\u0002\u0003\u0002\u0003\u0003\u0003\u0003\u0003\u0003\u0003\u0003\u0005\u0003C\n\u0003\u0003\u0004\u0003\u0004\u0003\u0004\u0003\u0004\u0003\u0004\u0007\u0004J\n\u0004\f\u0004\u000e\u0004M\u000b\u0004\u0003\u0005\u0003\u0005\u0003\u0006\u0003\u0006\u0003\u0006\u0003\u0006\u0003\u0006\u0007\u0006V\n\u0006\f\u0006\u000e\u0006Y\u000b\u0006\u0003\u0007\u0003\u0007\u0003\u0007\u0003\u0007\u0003\b\u0003\b\u0003\b\u0003\b\u0003\b\u0007\bd\n\b\f\b\u000e\bg\u000b\b\u0003\t\u0003\t\u0003\t\u0003\t\u0003\t\u0003\t\u0003\t\u0003\t\u0003\t\u0005\tr\n\t\u0003\n\u0003\n\u0003\n\u0003\n\u0003\n\u0003\n\u0003\n\u0003\n\u0003\n\u0003\n\u0003\n\u0005\n\u007f\n\n\u0003\u000b\u0003\u000b\u0003\u000b\u0003\u000b\u0007\u000b\u0085\n\u000b\f\u000b\u000e\u000b\u0088\u000b\u000b\u0003\u000b\u0003\u000b\u0003\u000b\u0003\u000b\u0003\u000b\u0003\u000b\u0007\u000b\u0090\n\u000b\f\u000b\u000e\u000b\u0093\u000b\u000b\u0003\u000b\u0003\u000b\u0005\u000b\u0097\n\u000b\u0003\u000b\u0003\u000b\u0003\u000b\u0003\u000b\u0007\u000b\u009d\n\u000b\f\u000b\u000e\u000b \u000b\u000b\u0003\u000b\u0003\u000b\u0003\u000b\u0003\u000b\u0005\u000b¦\n\u000b\u0003\f\u0003\f\u0003\f\u0003\f\u0003\f\u0006\f\u00ad\n\f\r\f\u000e\f®\u0003\f\u0003\f\u0003\r\u0003\r\u0003\r\u0003\r\u0003\r\u0003\r\u0003\r\u0003\r\u0003\r\u0005\r¼\n\r\u0003\u000e\u0003\u000e\u0003\u000e\u0007\u000eÁ\n\u000e\f\u000e\u000e\u000eÄ\u000b\u000e\u0003\u000f\u0003\u000f\u0003\u000f\u0005\u000fÉ\n\u000f\u0003\u0010\u0003\u0010\u0003\u0010\u0007\u0010Î\n\u0010\f\u0010\u000e\u0010Ñ\u000b\u0010\u0003\u0011\u0003\u0011\u0003\u0011\u0007\u0011Ö\n\u0011\f\u0011\u000e\u0011Ù\u000b\u0011\u0003\u0012\u0003\u0012\u0003\u0012\u0003\u0012\u0003\u0012\u0003\u0012\u0003\u0012\u0003\u0012\u0003\u0012\u0003\u0012\u0005\u0012å\n\u0012\u0003\u0013\u0003\u0013\u0003\u0013\u0003\u0013\u0007\u0013ë\n\u0013\f\u0013\u000e\u0013î\u000b\u0013\u0003\u0013\u0003\u0013\u0003\u0014\u0003\u0014\u0003\u0015\u0003\u0015\u0003\u0015\u0003\u0015\u0003\u0015\u0007\u0015ù\n\u0015\f\u0015\u000e\u0015ü\u000b\u0015\u0003\u0015\u0003\u0015\u0003\u0015\u0003\u0016\u0003\u0016\u0003\u0017\u0003\u0017\u0003\u0017\u0007\u0017Ć\n\u0017\f\u0017\u000e\u0017ĉ\u000b\u0017\u0003\u0017\u0003\u0017\u0003\u0018\u0003\u0018\u0003\u0018\u0003\u0018\u0003\u0018\u0003\u0018\u0003\u0018\u0003\u0018\u0003\u0018\u0003\u0018\u0003\u0018\u0005\u0018Ę\n\u0018\u0003\u0019\u0006\u0019ě\n\u0019\r\u0019\u000e\u0019Ĝ\u0003\u0019\u0005\u0019Ġ\n\u0019\u0003\u001a\u0006\u001aģ\n\u001a\r\u001a\u000e\u001aĤ\u0003\u001b\u0003\u001b\u0003\u001b\u0002\u0002\u001c\u0002\u0004\u0006\b\n\f\u000e\u0010\u0012\u0014\u0016\u0018\u001a\u001c\u001e \"$&(*,.024\u0002\u0006\u0003\u0002\u0007\u000f\u0003\u0002'*\u0003\u0002+-\u0003\u0002.7\u0002ı\u00029\u0003\u0002\u0002\u0002\u0004B\u0003\u0002\u0002\u0002\u0006D\u0003\u0002\u0002\u0002\bN\u0003\u0002\u0002\u0002\nP\u0003\u0002\u0002\u0002\fZ\u0003\u0002\u0002\u0002\u000e^\u0003\u0002\u0002\u0002\u0010q\u0003\u0002\u0002\u0002\u0012~\u0003\u0002\u0002\u0002\u0014\u0080\u0003\u0002\u0002\u0002\u0016§\u0003\u0002\u0002\u0002\u0018»\u0003\u0002\u0002\u0002\u001a½\u0003\u0002\u0002\u0002\u001cÈ\u0003\u0002\u0002\u0002\u001eÊ\u0003\u0002\u0002\u0002 Ò\u0003\u0002\u0002\u0002\"ä\u0003\u0002\u0002\u0002$æ\u0003\u0002\u0002\u0002&ñ\u0003\u0002\u0002\u0002(ó\u0003\u0002\u0002\u0002*Ā\u0003\u0002\u0002\u0002,Ă\u0003\u0002\u0002\u0002.ė\u0003\u0002\u0002\u00020ğ\u0003\u0002\u0002\u00022Ģ\u0003\u0002\u0002\u00024Ħ\u0003\u0002\u0002\u000268\u0005\u0004\u0003\u000276\u0003\u0002\u0002\u00028;\u0003\u0002\u0002\u000297\u0003\u0002\u0002\u00029:\u0003\u0002\u0002\u0002:<\u0003\u0002\u0002\u0002;9\u0003\u0002\u0002\u0002<=\u0007\u0003\u0002\u0002=\u0003\u0003\u0002\u0002\u0002>C\u0005\u0006\u0004\u0002?C\u0005\n\u0006\u0002@C\u0005\u000e\b\u0002AC\u0005\u0012\n\u0002B>\u0003\u0002\u0002\u0002B?\u0003\u0002\u0002\u0002B@\u0003\u0002\u0002\u0002BA\u0003\u0002\u0002\u0002C\u0005\u0003\u0002\u0002\u0002DE\u0007\u0004\u0002\u0002EF\u0007\u0005\u0002\u0002FK\u0005\b\u0005\u0002GH\u0007\u0006\u0002\u0002HJ\u0005\b\u0005\u0002IG\u0003\u0002\u0002\u0002JM\u0003\u0002\u0002\u0002KI\u0003\u0002\u0002\u0002KL\u0003\u0002\u0002\u0002L\u0007\u0003\u0002\u0002\u0002MK\u0003\u0002\u0002\u0002NO\t\u0002\u0002\u0002O\t\u0003\u0002\u0002\u0002PQ\u0007\u0010\u0002\u0002QR\u0007\u0005\u0002\u0002RW\u0005\f\u0007\u0002ST\u0007\u0006\u0002\u0002TV\u0005\f\u0007\u0002US\u0003\u0002\u0002\u0002VY\u0003\u0002\u0002\u0002WU\u0003\u0002\u0002\u0002WX\u0003\u0002\u0002\u0002X\u000b\u0003\u0002\u0002\u0002YW\u0003\u0002\u0002\u0002Z[\u0005\"\u0012\u0002[\\\u0007\u0011\u0002\u0002\\]\u0005\"\u0012\u0002]\r\u0003\u0002\u0002\u0002^_\u0007\u0012\u0002\u0002_`\u0007\u0005\u0002\u0002`e\u0005\u0010\t\u0002ab\u0007\u0006\u0002\u0002bd\u0005\u0010\t\u0002ca\u0003\u0002\u0002\u0002dg\u0003\u0002\u0002\u0002ec\u0003\u0002\u0002\u0002ef\u0003\u0002\u0002\u0002f\u000f\u0003\u0002\u0002\u0002ge\u0003\u0002\u0002\u0002hi\u00050\u0019\u0002ij\u0007\u0013\u0002\u0002jk\u00052\u001a\u0002kr\u0003\u0002\u0002\u0002lm\u00050\u0019\u0002mn\u0007\u0013\u0002\u0002no\u00052\u001a\u0002op\u0007\u0014\u0002\u0002pr\u0003\u0002\u0002\u0002qh\u0003\u0002\u0002\u0002ql\u0003\u0002\u0002\u0002r\u0011\u0003\u0002\u0002\u0002st\u0007\u0015\u0002\u0002tu\u00050\u0019\u0002uv\u0007\u0005\u0002\u0002vw\u0005\u0016\f\u0002wx\u0005\u0014\u000b\u0002x\u007f\u0003\u0002\u0002\u0002yz\u0007\u0015\u0002\u0002z{\u00050\u0019\u0002{|\u0007\u0005\u0002\u0002|}\u0005\u0014\u000b\u0002}\u007f\u0003\u0002\u0002\u0002~s\u0003\u0002\u0002\u0002~y\u0003\u0002\u0002\u0002\u007f\u0013\u0003\u0002\u0002\u0002\u0080\u0081\u0007\u0016\u0002\u0002\u0081\u0086\u0005\u0018\r\u0002\u0082\u0083\u0007\u0006\u0002\u0002\u0083\u0085\u0005\u0018\r\u0002\u0084\u0082\u0003\u0002\u0002\u0002\u0085\u0088\u0003\u0002\u0002\u0002\u0086\u0084\u0003\u0002\u0002\u0002\u0086\u0087\u0003\u0002\u0002\u0002\u0087\u0089\u0003\u0002\u0002\u0002\u0088\u0086\u0003\u0002\u0002\u0002\u0089\u0096\u0007\u0017\u0002\u0002\u008a\u0097\u0007\u0018\u0002\u0002\u008b\u008c\u0007\u0019\u0002\u0002\u008c\u0091\u0005\u0018\r\u0002\u008d\u008e\u0007\u0006\u0002\u0002\u008e\u0090\u0005\u0018\r\u0002\u008f\u008d\u0003\u0002\u0002\u0002\u0090\u0093\u0003\u0002\u0002\u0002\u0091\u008f\u0003\u0002\u0002\u0002\u0091\u0092\u0003\u0002\u0002\u0002\u0092\u0094\u0003\u0002\u0002\u0002\u0093\u0091\u0003\u0002\u0002\u0002\u0094\u0095\u0007\u001a\u0002\u0002\u0095\u0097\u0003\u0002\u0002\u0002\u0096\u008a\u0003\u0002\u0002\u0002\u0096\u008b\u0003\u0002\u0002\u0002\u0097¥\u0003\u0002\u0002\u0002\u0098\u0099\u0007\u0016\u0002\u0002\u0099\u009e\u0005\u0018\r\u0002\u009a\u009b\u0007\u0006\u0002\u0002\u009b\u009d\u0005\u0018\r\u0002\u009c\u009a\u0003\u0002\u0002\u0002\u009d \u0003\u0002\u0002\u0002\u009e\u009c\u0003\u0002\u0002\u0002\u009e\u009f\u0003\u0002\u0002\u0002\u009f¡\u0003\u0002\u0002\u0002 \u009e\u0003\u0002\u0002\u0002¡¢\u0007\u0017\u0002\u0002¢¦\u0003\u0002\u0002\u0002£¤\u0007\u0016\u0002\u0002¤¦\u0007\u0017\u0002\u0002¥\u0098\u0003\u0002\u0002\u0002¥£\u0003\u0002\u0002\u0002¦\u0015\u0003\u0002\u0002\u0002§¬\u0007\u001b\u0002\u0002¨©\u00050\u0019\u0002©ª\u0007\u0011\u0002\u0002ª«\u0005\"\u0012\u0002«\u00ad\u0003\u0002\u0002\u0002¬¨\u0003\u0002\u0002\u0002\u00ad®\u0003\u0002\u0002\u0002®¬\u0003\u0002\u0002\u0002®¯\u0003\u0002\u0002\u0002¯°\u0003\u0002\u0002\u0002°±\u0007\u001c\u0002\u0002±\u0017\u0003\u0002\u0002\u0002²³\u0005\u001c\u000f\u0002³´\u0007\u001d\u0002\u0002´µ\u0005\u001a\u000e\u0002µ¶\u0007\u001e\u0002\u0002¶¼\u0003\u0002\u0002\u0002·¸\u0005\u001c\u000f\u0002¸¹\u0007\u001d\u0002\u0002¹º\u0007\u001e\u0002\u0002º¼\u0003\u0002\u0002\u0002»²\u0003\u0002\u0002\u0002»·\u0003\u0002\u0002\u0002¼\u0019\u0003\u0002\u0002\u0002½Â\u0005\u001e\u0010\u0002¾¿\u0007\u0006\u0002\u0002¿Á\u0005\u001e\u0010\u0002À¾\u0003\u0002\u0002\u0002ÁÄ\u0003\u0002\u0002\u0002ÂÀ\u0003\u0002\u0002\u0002ÂÃ\u0003\u0002\u0002\u0002Ã\u001b\u0003\u0002\u0002\u0002ÄÂ\u0003\u0002\u0002\u0002ÅÆ\u0007\u001f\u0002\u0002ÆÉ\u00050\u0019\u0002ÇÉ\u00050\u0019\u0002ÈÅ\u0003\u0002\u0002\u0002ÈÇ\u0003\u0002\u0002\u0002É\u001d\u0003\u0002\u0002\u0002ÊÏ\u0005 \u0011\u0002ËÌ\u0007 \u0002\u0002ÌÎ\u0005 \u0011\u0002ÍË\u0003\u0002\u0002\u0002ÎÑ\u0003\u0002\u0002\u0002ÏÍ\u0003\u0002\u0002\u0002ÏÐ\u0003\u0002\u0002\u0002Ð\u001f\u0003\u0002\u0002\u0002ÑÏ\u0003\u0002\u0002\u0002Ò×\u0005\"\u0012\u0002ÓÔ\u0007!\u0002\u0002ÔÖ\u0005\"\u0012\u0002ÕÓ\u0003\u0002\u0002\u0002ÖÙ\u0003\u0002\u0002\u0002×Õ\u0003\u0002\u0002\u0002×Ø\u0003\u0002\u0002\u0002Ø!\u0003\u0002\u0002\u0002Ù×\u0003\u0002\u0002\u0002Úå\u0005$\u0013\u0002ÛÜ\u0007\u001d\u0002\u0002ÜÝ\u0005\u001e\u0010\u0002ÝÞ\u0007\u001e\u0002\u0002Þå\u0003\u0002\u0002\u0002ßå\u0005&\u0014\u0002àå\u0005(\u0015\u0002áå\u0005,\u0017\u0002âå\u0005.\u0018\u0002ãå\u0005\u0018\r\u0002äÚ\u0003\u0002\u0002\u0002äÛ\u0003\u0002\u0002\u0002äß\u0003\u0002\u0002\u0002äà\u0003\u0002\u0002\u0002äá\u0003\u0002\u0002\u0002äâ\u0003\u0002\u0002\u0002äã\u0003\u0002\u0002\u0002å#\u0003\u0002\u0002\u0002æç\u0007\"\u0002\u0002çì\u0005\u001e\u0010\u0002èé\u0007\u0006\u0002\u0002éë\u0005\u001e\u0010\u0002êè\u0003\u0002\u0002\u0002ëî\u0003\u0002\u0002\u0002ìê\u0003\u0002\u0002\u0002ìí\u0003\u0002\u0002\u0002íï\u0003\u0002\u0002\u0002îì\u0003\u0002\u0002\u0002ïð\u0007#\u0002\u0002ð%\u0003\u0002\u0002\u0002ñò\u0007$\u0002\u0002ò'\u0003\u0002\u0002\u0002óô\u0005*\u0016\u0002ôõ\u0007%\u0002\u0002õú\u0005\u001e\u0010\u0002ö÷\u0007\u0006\u0002\u0002÷ù\u0005\u001e\u0010\u0002øö\u0003\u0002\u0002\u0002ùü\u0003\u0002\u0002\u0002úø\u0003\u0002\u0002\u0002úû\u0003\u0002\u0002\u0002ûý\u0003\u0002\u0002\u0002üú\u0003\u0002\u0002\u0002ýþ\u0007&\u0002\u0002þÿ\u0005\"\u0012\u0002ÿ)\u0003\u0002\u0002\u0002Āā\t\u0003\u0002\u0002ā+\u0003\u0002\u0002\u0002Ăă\u0005*\u0016\u0002ăć\u0007\u001d\u0002\u0002ĄĆ\u0005\u001e\u0010\u0002ąĄ\u0003\u0002\u0002\u0002Ćĉ\u0003\u0002\u0002\u0002ćą\u0003\u0002\u0002\u0002ćĈ\u0003\u0002\u0002\u0002ĈĊ\u0003\u0002\u0002\u0002ĉć\u0003\u0002\u0002\u0002Ċċ\u0007\u001e\u0002\u0002ċ-\u0003\u0002\u0002\u0002Čč\u00079\u0002\u0002čĎ\u00050\u0019\u0002Ďď\u00079\u0002\u0002ďĘ\u0003\u0002\u0002\u0002Đđ\t\u0004\u0002\u0002đĘ\u00050\u0019\u0002Ēē\u0007:\u0002\u0002ēĔ\u00050\u0019\u0002Ĕĕ\u00079\u0002\u0002ĕĘ\u0003\u0002\u0002\u0002ĖĘ\u00050\u0019\u0002ėČ\u0003\u0002\u0002\u0002ėĐ\u0003\u0002\u0002\u0002ėĒ\u0003\u0002\u0002\u0002ėĖ\u0003\u0002\u0002\u0002Ę/\u0003\u0002\u0002\u0002ęě\u00078\u0002\u0002Ěę\u0003\u0002\u0002\u0002ěĜ\u0003\u0002\u0002\u0002ĜĚ\u0003\u0002\u0002\u0002Ĝĝ\u0003\u0002\u0002\u0002ĝĠ\u0003\u0002\u0002\u0002ĞĠ\u00054\u001b\u0002ğĚ\u0003\u0002\u0002\u0002ğĞ\u0003\u0002\u0002\u0002Ġ1\u0003\u0002\u0002\u0002ġģ\u00054\u001b\u0002Ģġ\u0003\u0002\u0002\u0002ģĤ\u0003\u0002\u0002\u0002ĤĢ\u0003\u0002\u0002\u0002Ĥĥ\u0003\u0002\u0002\u0002ĥ3\u0003\u0002\u0002\u0002Ħħ\t\u0005\u0002\u0002ħ5\u0003\u0002\u0002\u0002\u001c9BKWeq~\u0086\u0091\u0096\u009e¥®»ÂÈÏ×äìúćėĜğĤ"
                    .toCharArray());
    _decisionToDFA = new DFA[_ATN.getNumberOfDecisions()];

    for (i = 0; i < _ATN.getNumberOfDecisions(); ++i) {
      _decisionToDFA[i] = new DFA(_ATN.getDecisionState(i), i);
    }
  }

  /** The main entry point for the parser. */
  public static class TheoryContext extends ParserRuleContext {
    public List<ComponentContext> component() {
      return this.getRuleContexts(ComponentContext.class);
    }

    /**
     * Returns the i-th {@link ComponentContext} if it exists.
     *
     * @param i the index of the component to return
     * @return the i-th {@link ComponentContext} or null if it does not exist
     */
    public ComponentContext component(int i) {
      return this.getRuleContext(ComponentContext.class, i);
    }

    /**
     * Creates a new TheoryContext.
     *
     * @param parent the parent context
     * @param invokingState the state of the parser when this context was created
     */
    public TheoryContext(ParserRuleContext parent, int invokingState) {
      super(parent, invokingState);
    }

    /**
     * Returns the rule index for this context.
     *
     * @return the rule index for this context
     */
    public int getRuleIndex() {
      return 0;
    }

    /**
     * Accepts a visitor to this context.
     *
     * @param visitor the visitor to accept
     * @param <T> the return type of the visitor
     * @return the result of visiting this context
     */
    public <T> T accept(ParseTreeVisitor<? extends T> visitor) {
      return visitor instanceof TamarinVisitor
          ? (T) ((TamarinVisitor) visitor).visitTheory(this)
          : visitor.visitChildren(this);
    }
  }

  /**
   * Represents a component in the Tamarin theory. This includes built-in symbols, equations,
   * functions, and protocol rules. It extends {@link ParserRuleContext} to provide context for
   * parsing rules related to components.
   */
  public static class ComponentContext extends ParserRuleContext {

    /**
     * Returns the built-in symbols defined in this component.
     *
     * @return the {@link Built_inContext} containing built-in symbols
     */
    public Built_inContext built_in() {
      return this.getRuleContext(Built_inContext.class, 0);
    }

    /**
     * Returns the equations defined in this component.
     *
     * @return the {@link EquationsContext} containing equations
     */
    public EquationsContext equations() {
      return this.getRuleContext(EquationsContext.class, 0);
    }

    /**
     * Returns the functions defined in this component.
     *
     * @return the {@link FunctionsContext} containing functions
     */
    public FunctionsContext functions() {
      return this.getRuleContext(FunctionsContext.class, 0);
    }

    /**
     * Returns the protocol rules defined in this component.
     *
     * @return the {@link ProtocolruleContext} containing protocol rules
     */
    public ProtocolruleContext protocolrule() {
      return this.getRuleContext(ProtocolruleContext.class, 0);
    }

    /** Constructor for ComponentContext. */
    public ComponentContext(ParserRuleContext parent, int invokingState) {
      super(parent, invokingState);
    }

    /**
     * Returns the rule index for this context.
     *
     * @return the rule index for this context
     */
    public int getRuleIndex() {
      return 1;
    }

    /**
     * Accepts a visitor to this context.
     *
     * @param visitor the visitor to accept
     * @param <T> the return type of the visitor
     * @return the result of visiting this context
     */
    public <T> T accept(ParseTreeVisitor<? extends T> visitor) {
      return visitor instanceof TamarinVisitor
          ? (T) ((TamarinVisitor) visitor).visitComponent(this)
          : visitor.visitChildren(this);
    }
  }

  /**
   * Represents a built-in context in the Tamarin theory. It contains a list of built-in names. This
   * extends {@link ParserRuleContext} to provide context for parsing rules related to built-in
   * symbols.
   */
  public static class Built_inContext extends ParserRuleContext {

    /** Constructor for Built_inContext. */
    public Built_inContext(ParserRuleContext parent, int invokingState) {
      super(parent, invokingState);
    }

    /**
     * Returns rule index for this context.
     *
     * @return int rule index for this context
     */
    public int getRuleIndex() {
      return 2;
    }

    /**
     * Accepts a visitor to this context.
     *
     * @param visitor the visitor to accept
     * @param <T> the return type of the visitor
     * @return the result of visiting this context
     */
    public <T> T accept(ParseTreeVisitor<? extends T> visitor) {
      return visitor instanceof TamarinVisitor
          ? (T) ((TamarinVisitor) visitor).visitBuilt_in(this)
          : visitor.visitChildren(this);
    }
  }

  /**
   * Represents a list of equations in the Tamarin theory. It contains multiple equation symbols.
   * This extends {@link ParserRuleContext} to provide context for parsing rules related to
   * equations.
   */
  public static class EquationsContext extends ParserRuleContext {

    /** Constructor for EquationsContext. */
    public EquationsContext(ParserRuleContext parent, int invokingState) {
      super(parent, invokingState);
    }

    /**
     * Rule index for this context.
     *
     * @return int rule index for this context
     */
    public int getRuleIndex() {
      return 4;
    }

    /**
     * Accepts a visitor to this context.
     *
     * @param visitor the visitor to accept
     * @param <T> the return type of the visitor
     * @return the result of visiting this context
     */
    public <T> T accept(ParseTreeVisitor<? extends T> visitor) {
      return visitor instanceof TamarinVisitor
          ? (T) ((TamarinVisitor) visitor).visitEquations(this)
          : visitor.visitChildren(this);
    }
  }

  /**
   * Represents a list of functions in the Tamarin theory. It contains multiple function symbols.
   * This extends {@link ParserRuleContext} to provide context for parsing rules related to
   * functions.
   */
  public static class FunctionsContext extends ParserRuleContext {

    /**
     * Constructor for FunctionsContext.
     *
     * @param parent the parent context
     * @param invokingState the state of the parser when this context was created
     */
    public FunctionsContext(ParserRuleContext parent, int invokingState) {
      super(parent, invokingState);
    }

    /**
     * Returns the rule index for this context.
     *
     * @return the rule index for this context
     */
    public int getRuleIndex() {
      return 6;
    }

    /**
     * Accepts a visitor to this context.
     *
     * @param visitor the visitor to accept
     * @param <T> the return type of the visitor
     * @return the result of visiting this context
     */
    public <T> T accept(ParseTreeVisitor<? extends T> visitor) {
      return visitor instanceof TamarinVisitor
          ? (T) ((TamarinVisitor) visitor).visitFunctions(this)
          : visitor.visitChildren(this);
    }
  }

  /**
   * Represents a protocol rule in the Tamarin theory. It contains an identifier, a let block, and
   * optionally a generic rule. This extends {@link ParserRuleContext} to provide context for
   * parsing rules related to protocol rules.
   */
  public static class ProtocolruleContext extends ParserRuleContext {

    /**
     * Constructor for ProtocolruleContext.
     *
     * @param parent the parent context
     * @param invokingState the state of the parser when this context was created
     */
    public ProtocolruleContext(ParserRuleContext parent, int invokingState) {
      super(parent, invokingState);
    }

    /**
     * Rule index for this context.
     *
     * @return int rule index for this context
     */
    public int getRuleIndex() {
      return 8;
    }

    /**
     * Accepts a visitor to this context.
     *
     * @param visitor the visitor to accept
     * @param <T> the return type of the visitor
     * @return the result of visiting this context
     */
    public <T> T accept(ParseTreeVisitor<? extends T> visitor) {
      return visitor instanceof TamarinVisitor
          ? (T) ((TamarinVisitor) visitor).visitProtocolrule(this)
          : visitor.visitChildren(this);
    }
  }

  /**
   * Represents a built-in name in the Tamarin theory. This extends {@link ParserRuleContext} to
   * provide context for parsing rules related to built-in names.
   */
  public static class Builtin_nameContext extends ParserRuleContext {

    /**
     * COnstructor for Builtin_nameContext.
     *
     * @param parent the parent context
     * @param invokingState the state of the parser when this context was created
     */
    public Builtin_nameContext(ParserRuleContext parent, int invokingState) {
      super(parent, invokingState);
    }

    /**
     * Returns the rule index for this context.
     *
     * @return the rule index for this context
     */
    public int getRuleIndex() {
      return 3;
    }

    /**
     * Accepts a visitor to this context.
     *
     * @param visitor the visitor to accept
     * @param <T> the return type of the visitor
     * @return the result of visiting this context
     */
    public <T> T accept(ParseTreeVisitor<? extends T> visitor) {
      return visitor instanceof TamarinVisitor
          ? (T) ((TamarinVisitor) visitor).visitBuiltin_name(this)
          : visitor.visitChildren(this);
    }
  }

  /**
   * Represents an equation symbol in the Tamarin theory. It contains a list of terms that
   * constitute the equation. This extends {@link ParserRuleContext} to provide context for parsing
   * rules related to equations.
   */
  public static class Equation_symbolContext extends ParserRuleContext {

    /**
     * Constructor for Equation_symbolContext.
     *
     * @param parent the parent context
     * @param invokingState the state of the parser when this context was created
     */
    public Equation_symbolContext(ParserRuleContext parent, int invokingState) {
      super(parent, invokingState);
    }

    /**
     * Returns the rule index for this context.
     *
     * @return the rule index for this context
     */
    public int getRuleIndex() {
      return 5;
    }

    /**
     * Accepts a visitor to this context.
     *
     * @param visitor the visitor to accept
     * @param <T> the return type of the visitor
     * @return the result of visiting this context
     */
    public <T> T accept(ParseTreeVisitor<? extends T> visitor) {
      return visitor instanceof TamarinVisitor
          ? (T) ((TamarinVisitor) visitor).visitEquation_symbol(this)
          : visitor.visitChildren(this);
    }
  }

  /**
   * Represents a term in the Tamarin theory. This extends {@link ParserRuleContext} to provide
   * context for parsing rules related to terms.
   */
  public static class TermContext extends ParserRuleContext {

    /**
     * Returns the fact that represents a function symbol.
     *
     * @return the {@link Function_symbolContext} representing the function symbol
     */
    public FactContext fact() {
      return this.getRuleContext(FactContext.class, 0);
    }

    /**
     * Constructor for TermContext.
     *
     * @param parent the parent context
     * @param invokingState the state of the parser when this context was created
     */
    public TermContext(ParserRuleContext parent, int invokingState) {
      super(parent, invokingState);
    }

    /**
     * Returns the rule index for this context.
     *
     * @return the rule index for this context
     */
    public int getRuleIndex() {
      return 16;
    }

    /**
     * Accepts a visitor to this context.
     *
     * @param visitor the visitor to accept
     * @param <T> the return type of the visitor
     * @return the result of visiting this context
     */
    public <T> T accept(ParseTreeVisitor<? extends T> visitor) {
      return visitor instanceof TamarinVisitor
          ? (T) ((TamarinVisitor) visitor).visitTerm(this)
          : visitor.visitChildren(this);
    }
  }

  /**
   * Represents a function symbol in the Tamarin theory. It extends {@link ParserRuleContext} to
   * provide context for parsing rules related to function symbols.
   */
  public static class Function_symbolContext extends ParserRuleContext {

    /**
     * Constructor for Function_symbolContext.
     *
     * @param parent the parent context
     * @param invokingState the state of the parser when this context was created
     */
    public Function_symbolContext(ParserRuleContext parent, int invokingState) {
      super(parent, invokingState);
    }

    /**
     * Returns the rule index for this context.
     *
     * @return the rule index for this context
     */
    public int getRuleIndex() {
      return 7;
    }

    /**
     * Accepts a visitor to this context.
     *
     * @param visitor the visitor to accept
     * @param <T> the return type of the visitor
     * @return the result of visiting this context
     */
    public <T> T accept(ParseTreeVisitor<? extends T> visitor) {
      return visitor instanceof TamarinVisitor
          ? (T) ((TamarinVisitor) visitor).visitFunction_symbol(this)
          : visitor.visitChildren(this);
    }
  }

  /** Represents a digit in the Tamarin theory. */
  public static class IdentifierContext extends ParserRuleContext {

    /**
     * Constuctor for IdentifierContext.
     *
     * @param parent
     * @param invokingState
     */
    public IdentifierContext(ParserRuleContext parent, int invokingState) {
      super(parent, invokingState);
    }

    /**
     * Returns the rule index for this context.
     *
     * @return the rule index for this context
     */
    public int getRuleIndex() {
      return 23;
    }

    /**
     * Accepts a visitor to this context.
     *
     * @param visitor the visitor to accept
     * @param <T> the return type of the visitor
     * @return the result of visiting this context
     */
    public <T> T accept(ParseTreeVisitor<? extends T> visitor) {
      return visitor instanceof TamarinVisitor
          ? (T) ((TamarinVisitor) visitor).visitIdentifier(this)
          : visitor.visitChildren(this);
    }
  }

  /**
   * Represents natural context in the Tamarin theory. Extends {@link ParserRuleContext} to provide
   * context for parsing rules related to natural numbers.
   */
  public static class NaturalContext extends ParserRuleContext {

    /**
     * Constructor for NaturalContext.
     *
     * @param parent the parent context
     * @param invokingState the state of the parser when this context was created
     */
    public NaturalContext(ParserRuleContext parent, int invokingState) {
      super(parent, invokingState);
    }

    /**
     * Returns the rule index for this context.
     *
     * @return the rule index for this context
     */
    public int getRuleIndex() {
      return 24;
    }

    /**
     * Accepts a visitor to this context.
     *
     * @param visitor the visitor to accept
     * @param <T> the return type of the visitor
     * @return the result of visiting this context
     */
    public <T> T accept(ParseTreeVisitor<? extends T> visitor) {
      return visitor instanceof TamarinVisitor
          ? (T) ((TamarinVisitor) visitor).visitNatural(this)
          : visitor.visitChildren(this);
    }
  }

  /**
   * Represents a let block in the Tamarin theory. This extends {@link ParserRuleContext} to provide
   * context for parsing rules related to let blocks.
   */
  public static class Let_blockContext extends ParserRuleContext {

    /**
     * Constructor for Let_blockContext.
     *
     * @param parent the parent context
     * @param invokingState the state of the parser when this context was created
     */
    public Let_blockContext(ParserRuleContext parent, int invokingState) {
      super(parent, invokingState);
    }

    /**
     * Returns the rule index for this context.
     *
     * @return the rule index for this context
     */
    public int getRuleIndex() {
      return 10;
    }

    /**
     * Accepts a visitor to this context.
     *
     * @param visitor the visitor to accept
     * @param <T> the return type of the visitor
     * @return the result of visiting this context
     */
    public <T> T accept(ParseTreeVisitor<? extends T> visitor) {
      return visitor instanceof TamarinVisitor
          ? (T) ((TamarinVisitor) visitor).visitLet_block(this)
          : visitor.visitChildren(this);
    }
  }

  /**
   * Represents a generic rule in the Tamarin theory. It contains a list of facts that define the
   * rule. This extends {@link ParserRuleContext} to provide context for parsing rules related to
   * generic rules.
   */
  public static class GenericruleContext extends ParserRuleContext {

    /**
     * Get the rule context.
     *
     * @return the list of facts in this generic rule
     */
    public List<FactContext> fact() {
      return this.getRuleContexts(FactContext.class);
    }

    /**
     * Returns the i-th {@link FactContext} if it exists.
     *
     * @param i the index of the fact to return
     * @return the i-th {@link FactContext} or null if it does not exist
     */
    public FactContext fact(int i) {
      return this.getRuleContext(FactContext.class, i);
    }

    /**
     * Constructor for GenericruleContext.
     *
     * @param parent the parent context
     * @param invokingState the state of the parser when this context was created
     */
    public GenericruleContext(ParserRuleContext parent, int invokingState) {
      super(parent, invokingState);
    }

    /**
     * Returns the rule index for this context.
     *
     * @return the rule index for this context
     */
    public int getRuleIndex() {
      return 9;
    }

    /**
     * Accepts a visitor to this context.
     *
     * @param visitor the visitor to accept
     * @param <T> the return type of the visitor
     * @return the result of visiting this context
     */
    public <T> T accept(ParseTreeVisitor<? extends T> visitor) {
      return visitor instanceof TamarinVisitor
          ? (T) ((TamarinVisitor) visitor).visitGenericrule(this)
          : visitor.visitChildren(this);
    }
  }

  /**
   * Represents a fact in the Tamarin theory. This extends {@link ParserRuleContext} to provide
   * context for parsing rules related to facts.
   */
  public static class FactContext extends ParserRuleContext {

    /**
     * Constructor for FactContext.
     *
     * @param parent the parent context
     * @param invokingState the state of the parser when this context was created
     */
    public FactContext(ParserRuleContext parent, int invokingState) {
      super(parent, invokingState);
    }

    /**
     * Gets the identifier of the fact.
     *
     * @return the identifier context of the fact
     */
    public int getRuleIndex() {
      return 11;
    }

    /**
     * Accepts a visitor to this context.
     *
     * @param visitor the visitor to accept
     * @param <T> the return type of the visitor
     * @return the result of visiting this context
     */
    public <T> T accept(ParseTreeVisitor<? extends T> visitor) {
      return visitor instanceof TamarinVisitor
          ? (T) ((TamarinVisitor) visitor).visitFact(this)
          : visitor.visitChildren(this);
    }
  }

  /**
   * Represents a fact identifier in the Tamarin theory. It contains an identifier that represents
   * the fact. This extends {@link ParserRuleContext} to provide context for parsing rules related
   * to fact identifiers.
   */
  public static class Fact_identifierContext extends ParserRuleContext {

    /** Constructor for Fact_identifierContext. */
    public Fact_identifierContext(ParserRuleContext parent, int invokingState) {
      super(parent, invokingState);
    }

    /**
     * Returns the identifier of the fact.
     *
     * @return the identifier context of the fact
     */
    public int getRuleIndex() {
      return 13;
    }

    /**
     * Accepts a visitor to this context.
     *
     * @param visitor the visitor to accept
     * @param <T> the return type of the visitor
     * @return the result of visiting this context
     */
    public <T> T accept(ParseTreeVisitor<? extends T> visitor) {
      return visitor instanceof TamarinVisitor
          ? (T) ((TamarinVisitor) visitor).visitFact_identifier(this)
          : visitor.visitChildren(this);
    }
  }

  /**
   * Represents a collection of terms in the Tamarin theory. It extends {@link ParserRuleContext} to
   * provide context for parsing rules related to terms.
   */
  public static class TermsContext extends ParserRuleContext {

    /**
     * Constructor for TermsContext.
     *
     * @param parent the parent context
     * @param invokingState the state of the parser when this context was created
     */
    public TermsContext(ParserRuleContext parent, int invokingState) {
      super(parent, invokingState);
    }

    /**
     * Returns the rule index for this context.
     *
     * @return rule index for this context
     */
    public int getRuleIndex() {
      return 12;
    }

    /**
     * Accepts a visitor to this context.
     *
     * @param visitor the visitor to accept
     * @param <T> the return type of the visitor
     * @return the result of visiting this context
     */
    public <T> T accept(ParseTreeVisitor<? extends T> visitor) {
      return visitor instanceof TamarinVisitor
          ? (T) ((TamarinVisitor) visitor).visitTerms(this)
          : visitor.visitChildren(this);
    }
  }

  /**
   * Represents a collection of terms in the Tamarin theory. It extends {@link ParserRuleContext} to
   * provide context for parsing rules related to multiple terms.
   */
  public static class MulttermContext extends ParserRuleContext {

    /**
     * Constructor for MulttermContext.
     *
     * @param parent the parent context
     * @param invokingState the state of the parser when this context was created
     */
    public MulttermContext(ParserRuleContext parent, int invokingState) {
      super(parent, invokingState);
    }

    /**
     * Returns the rule index for this context.
     *
     * @return the rule index for this context
     */
    public int getRuleIndex() {
      return 14;
    }

    /**
     * Accepts a visitor to this context.
     *
     * @param visitor the visitor to accept
     * @param <T> the return type of the visitor
     * @return the result of visiting this context
     */
    public <T> T accept(ParseTreeVisitor<? extends T> visitor) {
      return visitor instanceof TamarinVisitor
          ? (T) ((TamarinVisitor) visitor).visitMultterm(this)
          : visitor.visitChildren(this);
    }
  }

  /**
   * Represents an expression term in the Tamarin theory. It contains a list of terms that
   * constitute the expression. This extends {@link ParserRuleContext} to provide context for
   * parsing rules related to expression terms.
   */
  public static class ExptermContext extends ParserRuleContext {

    /**
     * Constructor for ExptermContext.
     *
     * @param parent the parent context
     * @param invokingState the state of the parser when this context was created
     */
    public ExptermContext(ParserRuleContext parent, int invokingState) {
      super(parent, invokingState);
    }

    /**
     * Returns index of the rule for this context.
     *
     * @return the rule index for this context
     */
    public int getRuleIndex() {
      return 15;
    }

    /**
     * Accepts a visitor to this context.
     *
     * @param visitor the visitor to accept
     * @param <T> the return type of the visitor
     * @return the result of visiting this context
     */
    public <T> T accept(ParseTreeVisitor<? extends T> visitor) {
      return visitor instanceof TamarinVisitor
          ? (T) ((TamarinVisitor) visitor).visitExpterm(this)
          : visitor.visitChildren(this);
    }
  }

  /**
   * Represents a group of terms in the Tamarin theory. It contains multiple terms that are grouped
   * together. This extends {@link ParserRuleContext} to provide context for parsing rules related
   * to groups of terms.
   */
  public static class Group_of_termsContext extends ParserRuleContext {

    /**
     * Constructor for Group_of_termsContext.
     *
     * @param parent the parent context
     * @param invokingState the state of the parser when this context was created
     */
    public Group_of_termsContext(ParserRuleContext parent, int invokingState) {
      super(parent, invokingState);
    }

    /**
     * Returns the rule index for this context.
     *
     * @return the rule index for this context
     */
    public int getRuleIndex() {
      return 17;
    }

    /**
     * Accepts a visitor to this context.
     *
     * @param visitor the visitor to accept
     * @param <T> the return type of the visitor
     * @return the result of visiting this context
     */
    public <T> T accept(ParseTreeVisitor<? extends T> visitor) {
      return visitor instanceof TamarinVisitor
          ? (T) ((TamarinVisitor) visitor).visitGroup_of_terms(this)
          : visitor.visitChildren(this);
    }
  }

  /**
   * Represents a nullary function in the Tamarin theory. It extends {@link ParserRuleContext} to
   * provide context for parsing rules related to nullary functions.
   */
  public static class Nullary_funContext extends ParserRuleContext {

    /**
     * Constructor for Nullary_funContext.
     *
     * @param parent the parent context
     * @param invokingState the state of the parser when this context was created
     */
    public Nullary_funContext(ParserRuleContext parent, int invokingState) {
      super(parent, invokingState);
    }

    /**
     * Returns the rule index for this context.
     *
     * @return the rule index for this context
     */
    public int getRuleIndex() {
      return 18;
    }

    /**
     * Accepts a visitor to this context.
     *
     * @param visitor the visitor to accept
     * @param <T> the return type of the visitor
     * @return the result of visiting this context
     */
    public <T> T accept(ParseTreeVisitor<? extends T> visitor) {
      return visitor instanceof TamarinVisitor
          ? (T) ((TamarinVisitor) visitor).visitNullary_fun(this)
          : visitor.visitChildren(this);
    }
  }

  /**
   * Represents a binary application in the Tamarin theory. It contains a binary function and a list
   * of multiple terms. This extends {@link ParserRuleContext} to provide context for parsing rules
   * related to binary applications.
   */
  public static class Binary_appContext extends ParserRuleContext {

    /**
     * Constructor for Binary_appContext.
     *
     * @param parent the parent context
     * @param invokingState the state of the parser when this context was created
     */
    public Binary_appContext(ParserRuleContext parent, int invokingState) {
      super(parent, invokingState);
    }

    /**
     * Returns index of the rule for this context.
     *
     * @return the rule index for this context
     */
    public int getRuleIndex() {
      return 19;
    }

    /**
     * Accepts a visitor to this context.
     *
     * @param visitor the visitor to accept
     * @param <T> the return type of the visitor
     * @return the result of visiting this context
     */
    public <T> T accept(ParseTreeVisitor<? extends T> visitor) {
      return visitor instanceof TamarinVisitor
          ? (T) ((TamarinVisitor) visitor).visitBinary_app(this)
          : visitor.visitChildren(this);
    }
  }

  /**
   * Represents an n-ary application in the Tamarin theory. It contains a binary function and a list
   * of multiple terms. This extends {@link ParserRuleContext} to provide context for parsing rules
   * related to n-ary applications.
   */
  public static class Nary_appContext extends ParserRuleContext {

    /**
     * Constructor for Nary_appContext.
     *
     * @param parent the parent context
     * @param invokingState the state of the parser when this context was created
     */
    public Nary_appContext(ParserRuleContext parent, int invokingState) {
      super(parent, invokingState);
    }

    /**
     * Returns index of the rule for this context.
     *
     * @return the rule index for this context
     */
    public int getRuleIndex() {
      return 21;
    }

    /**
     * Accepts a visitor to this context.
     *
     * @param visitor the visitor to accept
     * @param <T> the return type of the visitor
     * @return the result of visiting this context
     */
    public <T> T accept(ParseTreeVisitor<? extends T> visitor) {
      return visitor instanceof TamarinVisitor
          ? (T) ((TamarinVisitor) visitor).visitNary_app(this)
          : visitor.visitChildren(this);
    }
  }

  /**
   * Represents a literal in the Tamarin theory. This extends {@link ParserRuleContext} to provide
   * context for parsing rules related to literals.
   */
  public static class LiteralContext extends ParserRuleContext {

    /**
     * Constructor for LiteralContext.
     *
     * @param parent the parent context
     * @param invokingState the state of the parser when this context was created
     */
    public LiteralContext(ParserRuleContext parent, int invokingState) {
      super(parent, invokingState);
    }

    /**
     * Returns the rule index for this context.
     *
     * @return the rule index for this context
     */
    public int getRuleIndex() {
      return 22;
    }

    /**
     * Accepts a visitor to this context.
     *
     * @param visitor the visitor to accept
     * @param <T> the return type of the visitor
     * @return the result of visiting this context
     */
    public <T> T accept(ParseTreeVisitor<? extends T> visitor) {
      return visitor instanceof TamarinVisitor
          ? (T) ((TamarinVisitor) visitor).visitLiteral(this)
          : visitor.visitChildren(this);
    }
  }

  /**
   * Represents a binary function in the Tamarin theory. It extends {@link ParserRuleContext} to
   * provide context for parsing rules related to binary functions.
   */
  public static class Binary_funContext extends ParserRuleContext {

    /**
     * Constructor for Binary_funContext.
     *
     * @param parent the parent context
     * @param invokingState the state of the parser when this context was created
     */
    public Binary_funContext(ParserRuleContext parent, int invokingState) {
      super(parent, invokingState);
    }

    /**
     * Returns the rule index for this context.
     *
     * @return the rule index for this context
     */
    public int getRuleIndex() {
      return 20;
    }

    /**
     * Accepts a visitor to this context.
     *
     * @param visitor the visitor to accept
     * @param <T> the return type of the visitor
     * @return the result of visiting this context
     */
    public <T> T accept(ParseTreeVisitor<? extends T> visitor) {
      return visitor instanceof TamarinVisitor
          ? (T) ((TamarinVisitor) visitor).visitBinary_fun(this)
          : visitor.visitChildren(this);
    }
  }

  /**
   * Represents a digit in the Tamarin theory. This extends {@link ParserRuleContext} to provide
   * context for parsing rules related to digits.
   */
  public static class DigitContext extends ParserRuleContext {

    /**
     * Constructor for DigitContext.
     *
     * @param parent the parent context
     * @param invokingState the state of the parser when this context was created
     */
    public DigitContext(ParserRuleContext parent, int invokingState) {
      super(parent, invokingState);
    }

    /**
     * Returns the rule index for this context.
     *
     * @return the rule index for this context
     */
    public int getRuleIndex() {
      return 25;
    }

    /**
     * Accepts a visitor to this context.
     *
     * @param visitor the visitor to accept
     * @param <T> the return type of the visitor
     * @return the result of visiting this context
     */
    public <T> T accept(ParseTreeVisitor<? extends T> visitor) {
      return visitor instanceof TamarinVisitor
          ? (T) ((TamarinVisitor) visitor).visitDigit(this)
          : visitor.visitChildren(this);
    }
  }
}
